version: "2"

linters:
  default: standard
  exclusions:
    paths:
      - internal/transport/pb
      - api/v1alpha1/zz_generated.deepcopy.go

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - internal/transport/pb
