// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: urutau/v1/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── Handshake ────────────────────────────────────────────────────────────
type WorkerPhase int32

const (
	WorkerPhase_WORKER_PHASE_UNSPECIFIED  WorkerPhase = 0
	WorkerPhase_WORKER_PHASE_STARTING     WorkerPhase = 1
	WorkerPhase_WORKER_PHASE_SNAPSHOTTING WorkerPhase = 2 // → coordinator re-issues pending chunks
	WorkerPhase_WORKER_PHASE_STREAMING    WorkerPhase = 3 // → coordinator opens an interval reader
)

// Enum value maps for WorkerPhase.
var (
	WorkerPhase_name = map[int32]string{
		0: "WORKER_PHASE_UNSPECIFIED",
		1: "WORKER_PHASE_STARTING",
		2: "WORKER_PHASE_SNAPSHOTTING",
		3: "WORKER_PHASE_STREAMING",
	}
	WorkerPhase_value = map[string]int32{
		"WORKER_PHASE_UNSPECIFIED":  0,
		"WORKER_PHASE_STARTING":     1,
		"WORKER_PHASE_SNAPSHOTTING": 2,
		"WORKER_PHASE_STREAMING":    3,
	}
)

func (x WorkerPhase) Enum() *WorkerPhase {
	p := new(WorkerPhase)
	*p = x
	return p
}

func (x WorkerPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_urutau_v1_control_proto_enumTypes[0].Descriptor()
}

func (WorkerPhase) Type() protoreflect.EnumType {
	return &file_urutau_v1_control_proto_enumTypes[0]
}

func (x WorkerPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerPhase.Descriptor instead.
func (WorkerPhase) EnumDescriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{0}
}

// ── Assignment ───────────────────────────────────────────────────────────
type WriteMode int32

const (
	WriteMode_WRITE_MODE_UNSPECIFIED WriteMode = 0
	WriteMode_WRITE_MODE_UPSERT      WriteMode = 1
	WriteMode_WRITE_MODE_APPEND      WriteMode = 2
)

// Enum value maps for WriteMode.
var (
	WriteMode_name = map[int32]string{
		0: "WRITE_MODE_UNSPECIFIED",
		1: "WRITE_MODE_UPSERT",
		2: "WRITE_MODE_APPEND",
	}
	WriteMode_value = map[string]int32{
		"WRITE_MODE_UNSPECIFIED": 0,
		"WRITE_MODE_UPSERT":      1,
		"WRITE_MODE_APPEND":      2,
	}
)

func (x WriteMode) Enum() *WriteMode {
	p := new(WriteMode)
	*p = x
	return p
}

func (x WriteMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteMode) Descriptor() protoreflect.EnumDescriptor {
	return file_urutau_v1_control_proto_enumTypes[1].Descriptor()
}

func (WriteMode) Type() protoreflect.EnumType {
	return &file_urutau_v1_control_proto_enumTypes[1]
}

func (x WriteMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteMode.Descriptor instead.
func (WriteMode) EnumDescriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{1}
}

// ── Errors ───────────────────────────────────────────────────────────────
type ErrorClass int32

const (
	ErrorClass_ERROR_CLASS_UNSPECIFIED  ErrorClass = 0
	ErrorClass_ERROR_CLASS_TRANSIENT    ErrorClass = 1 // retry with backoff
	ErrorClass_ERROR_CLASS_WORKER_FATAL ErrorClass = 2 // kill the worker → reset
	ErrorClass_ERROR_CLASS_JOB_FATAL    ErrorClass = 3 // terminal
	ErrorClass_ERROR_CLASS_NEEDS_HUMAN  ErrorClass = 4 // pause, wait for intervention
)

// Enum value maps for ErrorClass.
var (
	ErrorClass_name = map[int32]string{
		0: "ERROR_CLASS_UNSPECIFIED",
		1: "ERROR_CLASS_TRANSIENT",
		2: "ERROR_CLASS_WORKER_FATAL",
		3: "ERROR_CLASS_JOB_FATAL",
		4: "ERROR_CLASS_NEEDS_HUMAN",
	}
	ErrorClass_value = map[string]int32{
		"ERROR_CLASS_UNSPECIFIED":  0,
		"ERROR_CLASS_TRANSIENT":    1,
		"ERROR_CLASS_WORKER_FATAL": 2,
		"ERROR_CLASS_JOB_FATAL":    3,
		"ERROR_CLASS_NEEDS_HUMAN":  4,
	}
)

func (x ErrorClass) Enum() *ErrorClass {
	p := new(ErrorClass)
	*p = x
	return p
}

func (x ErrorClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorClass) Descriptor() protoreflect.EnumDescriptor {
	return file_urutau_v1_control_proto_enumTypes[2].Descriptor()
}

func (ErrorClass) Type() protoreflect.EnumType {
	return &file_urutau_v1_control_proto_enumTypes[2]
}

func (x ErrorClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorClass.Descriptor instead.
func (ErrorClass) EnumDescriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{2}
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Ack
	//	*WorkerMessage_ChunkReady
	//	*WorkerMessage_ChunkFailed
	//	*WorkerMessage_Error
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_urutau_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *WorkerMessage) GetChunkReady() *ChunkReady {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_ChunkReady); ok {
			return x.ChunkReady
		}
	}
	return nil
}

func (x *WorkerMessage) GetChunkFailed() *ChunkFailed {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_ChunkFailed); ok {
			return x.ChunkFailed
		}
	}
	return nil
}

func (x *WorkerMessage) GetError() *WorkerError {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type WorkerMessage_ChunkReady struct {
	ChunkReady *ChunkReady `protobuf:"bytes,3,opt,name=chunk_ready,json=chunkReady,proto3,oneof"`
}

type WorkerMessage_ChunkFailed struct {
	ChunkFailed *ChunkFailed `protobuf:"bytes,4,opt,name=chunk_failed,json=chunkFailed,proto3,oneof"`
}

type WorkerMessage_Error struct {
	Error *WorkerError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Msg() {}

func (*WorkerMessage_Ack) isWorkerMessage_Msg() {}

func (*WorkerMessage_ChunkReady) isWorkerMessage_Msg() {}

func (*WorkerMessage_ChunkFailed) isWorkerMessage_Msg() {}

func (*WorkerMessage_Error) isWorkerMessage_Msg() {}

type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*CoordinatorMessage_Assign
	//	*CoordinatorMessage_Chunk
	Msg           isCoordinatorMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_urutau_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinatorMessage) GetMsg() isCoordinatorMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CoordinatorMessage) GetAssign() *Assignment {
	if x != nil {
		if x, ok := x.Msg.(*CoordinatorMessage_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetChunk() *ChunkRequest {
	if x != nil {
		if x, ok := x.Msg.(*CoordinatorMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isCoordinatorMessage_Msg interface {
	isCoordinatorMessage_Msg()
}

type CoordinatorMessage_Assign struct {
	Assign *Assignment `protobuf:"bytes,1,opt,name=assign,proto3,oneof"`
}

type CoordinatorMessage_Chunk struct {
	Chunk *ChunkRequest `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*CoordinatorMessage_Assign) isCoordinatorMessage_Msg() {}

func (*CoordinatorMessage_Chunk) isCoordinatorMessage_Msg() {}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControlMessage_Pause
	//	*ControlMessage_Shutdown
	Msg           isControlMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_urutau_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ControlMessage) GetMsg() isControlMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControlMessage) GetPause() *Pause {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *ControlMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isControlMessage_Msg interface {
	isControlMessage_Msg()
}

type ControlMessage_Pause struct {
	Pause *Pause `protobuf:"bytes,1,opt,name=pause,proto3,oneof"`
}

type ControlMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,2,opt,name=shutdown,proto3,oneof"`
}

func (*ControlMessage_Pause) isControlMessage_Msg() {}

func (*ControlMessage_Shutdown) isControlMessage_Msg() {}

type Hello struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkerName  string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	PodUid      string                 `protobuf:"bytes,2,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`                // detects zombies
	Epoch       uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`                               // bumped on every reset
	Phase       WorkerPhase            `protobuf:"varint,4,opt,name=phase,proto3,enum=urutau.v1.WorkerPhase" json:"phase,omitempty"`    // decides the recovery path
	ImageDigest string                 `protobuf:"bytes,5,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"` // detects image skew
	// target_table → committed position, read from the Iceberg table property.
	Committed map[string]string `protobuf:"bytes,6,rep,name=committed,proto3" json:"committed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Chunk ids already completed, per source table. Lets the coordinator
	// re-issue only what is pending after a mid-snapshot restart.
	CompletedChunks map[string]*ChunkIds `protobuf:"bytes,7,rep,name=completed_chunks,json=completedChunks,proto3" json:"completed_chunks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_urutau_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Hello) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *Hello) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Hello) GetPhase() WorkerPhase {
	if x != nil {
		return x.Phase
	}
	return WorkerPhase_WORKER_PHASE_UNSPECIFIED
}

func (x *Hello) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *Hello) GetCommitted() map[string]string {
	if x != nil {
		return x.Committed
	}
	return nil
}

func (x *Hello) GetCompletedChunks() map[string]*ChunkIds {
	if x != nil {
		return x.CompletedChunks
	}
	return nil
}

type ChunkIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint32               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkIds) Reset() {
	*x = ChunkIds{}
	mi := &file_urutau_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkIds) ProtoMessage() {}

func (x *ChunkIds) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkIds.ProtoReflect.Descriptor instead.
func (*ChunkIds) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkIds) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type TableAssignment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SourceTable       string                 `protobuf:"bytes,1,opt,name=source_table,json=sourceTable,proto3" json:"source_table,omitempty"` // "shop.orders"
	TargetTable       string                 `protobuf:"bytes,2,opt,name=target_table,json=targetTable,proto3" json:"target_table,omitempty"` // "lakehouse.orders"
	WriteMode         WriteMode              `protobuf:"varint,3,opt,name=write_mode,json=writeMode,proto3,enum=urutau.v1.WriteMode" json:"write_mode,omitempty"`
	PrimaryKey        []string               `protobuf:"bytes,4,rep,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`           // equality-delete key; required on upsert
	PartitionBy       []string               `protobuf:"bytes,5,rep,name=partition_by,json=partitionBy,proto3" json:"partition_by,omitempty"`        // native Iceberg transforms
	IncludeBefore     bool                   `protobuf:"varint,6,opt,name=include_before,json=includeBefore,proto3" json:"include_before,omitempty"` // derived: true only with a mutable-column filter
	CreateIfNotExists bool                   `protobuf:"varint,7,opt,name=create_if_not_exists,json=createIfNotExists,proto3" json:"create_if_not_exists,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TableAssignment) Reset() {
	*x = TableAssignment{}
	mi := &file_urutau_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableAssignment) ProtoMessage() {}

func (x *TableAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableAssignment.ProtoReflect.Descriptor instead.
func (*TableAssignment) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *TableAssignment) GetSourceTable() string {
	if x != nil {
		return x.SourceTable
	}
	return ""
}

func (x *TableAssignment) GetTargetTable() string {
	if x != nil {
		return x.TargetTable
	}
	return ""
}

func (x *TableAssignment) GetWriteMode() WriteMode {
	if x != nil {
		return x.WriteMode
	}
	return WriteMode_WRITE_MODE_UNSPECIFIED
}

func (x *TableAssignment) GetPrimaryKey() []string {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *TableAssignment) GetPartitionBy() []string {
	if x != nil {
		return x.PartitionBy
	}
	return nil
}

func (x *TableAssignment) GetIncludeBefore() bool {
	if x != nil {
		return x.IncludeBefore
	}
	return false
}

func (x *TableAssignment) GetCreateIfNotExists() bool {
	if x != nil {
		return x.CreateIfNotExists
	}
	return false
}

type BatchConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxBytes      int64                  `protobuf:"varint,1,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	MaxInterval   *durationpb.Duration   `protobuf:"bytes,2,opt,name=max_interval,json=maxInterval,proto3" json:"max_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchConfig) Reset() {
	*x = BatchConfig{}
	mi := &file_urutau_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchConfig) ProtoMessage() {}

func (x *BatchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchConfig.ProtoReflect.Descriptor instead.
func (*BatchConfig) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *BatchConfig) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *BatchConfig) GetMaxInterval() *durationpb.Duration {
	if x != nil {
		return x.MaxInterval
	}
	return nil
}

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerName    string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Ticket        []byte                 `protobuf:"bytes,4,opt,name=ticket,proto3" json:"ticket,omitempty"` // Flight DoGet ticket
	Tables        []*TableAssignment     `protobuf:"bytes,5,rep,name=tables,proto3" json:"tables,omitempty"`
	Batching      *BatchConfig           `protobuf:"bytes,6,opt,name=batching,proto3" json:"batching,omitempty"`                       // already resolved, including worker override
	ResumeFrom    string                 `protobuf:"bytes,7,opt,name=resume_from,json=resumeFrom,proto3" json:"resume_from,omitempty"` // min() position this worker resumes from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_urutau_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *Assignment) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Assignment) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Assignment) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Assignment) GetTicket() []byte {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *Assignment) GetTables() []*TableAssignment {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *Assignment) GetBatching() *BatchConfig {
	if x != nil {
		return x.Batching
	}
	return nil
}

func (x *Assignment) GetResumeFrom() string {
	if x != nil {
		return x.ResumeFrom
	}
	return ""
}

// ── Acks ─────────────────────────────────────────────────────────────────
type Ack struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchId        uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Epoch          uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`      // stale-epoch acks are rejected
	Table          string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`       // target table
	Position       string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"` // position AFTER the Iceberg commit
	Rows           uint64                 `protobuf:"varint,5,opt,name=rows,proto3" json:"rows,omitempty"`
	Deletes        uint64                 `protobuf:"varint,6,opt,name=deletes,proto3" json:"deletes,omitempty"` // equality deletes written — feeds collapse_ratio
	CommitDuration *durationpb.Duration   `protobuf:"bytes,7,opt,name=commit_duration,json=commitDuration,proto3" json:"commit_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_urutau_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *Ack) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Ack) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Ack) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Ack) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Ack) GetDeletes() uint64 {
	if x != nil {
		return x.Deletes
	}
	return 0
}

func (x *Ack) GetCommitDuration() *durationpb.Duration {
	if x != nil {
		return x.CommitDuration
	}
	return nil
}

// ── DBLog chunks ─────────────────────────────────────────────────────────
type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"` // source table
	ChunkId       uint32                 `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Low           []byte                 `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`                                           // lower PK bound (lexicographic tuple)
	High          []byte                 `protobuf:"bytes,4,opt,name=high,proto3" json:"high,omitempty"`                                         // upper PK bound
	InclusiveHigh bool                   `protobuf:"varint,5,opt,name=inclusive_high,json=inclusiveHigh,proto3" json:"inclusive_high,omitempty"` // true only on the last chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_urutau_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ChunkRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ChunkRequest) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *ChunkRequest) GetLow() []byte {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *ChunkRequest) GetHigh() []byte {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *ChunkRequest) GetInclusiveHigh() bool {
	if x != nil {
		return x.InclusiveHigh
	}
	return false
}

type ChunkReady struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Table           string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"` // disambiguates parallel chunks
	ChunkId         uint32                 `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Rows            uint64                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	DroppedByWindow uint64                 `protobuf:"varint,4,opt,name=dropped_by_window,json=droppedByWindow,proto3" json:"dropped_by_window,omitempty"` // proves DBLog is working
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChunkReady) Reset() {
	*x = ChunkReady{}
	mi := &file_urutau_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkReady) ProtoMessage() {}

func (x *ChunkReady) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkReady.ProtoReflect.Descriptor instead.
func (*ChunkReady) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *ChunkReady) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ChunkReady) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *ChunkReady) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ChunkReady) GetDroppedByWindow() uint64 {
	if x != nil {
		return x.DroppedByWindow
	}
	return 0
}

type ChunkFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	ChunkId       uint32                 `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Class         ErrorClass             `protobuf:"varint,3,opt,name=class,proto3,enum=urutau.v1.ErrorClass" json:"class,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkFailed) Reset() {
	*x = ChunkFailed{}
	mi := &file_urutau_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkFailed) ProtoMessage() {}

func (x *ChunkFailed) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkFailed.ProtoReflect.Descriptor instead.
func (*ChunkFailed) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *ChunkFailed) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ChunkFailed) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *ChunkFailed) GetClass() ErrorClass {
	if x != nil {
		return x.Class
	}
	return ErrorClass_ERROR_CLASS_UNSPECIFIED
}

func (x *ChunkFailed) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type WorkerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         ErrorClass             `protobuf:"varint,1,opt,name=class,proto3,enum=urutau.v1.ErrorClass" json:"class,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"` // stable machine-readable id, e.g. "commit_exhausted"
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Table         string                 `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerError) Reset() {
	*x = WorkerError{}
	mi := &file_urutau_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerError) ProtoMessage() {}

func (x *WorkerError) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerError.ProtoReflect.Descriptor instead.
func (*WorkerError) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *WorkerError) GetClass() ErrorClass {
	if x != nil {
		return x.Class
	}
	return ErrorClass_ERROR_CLASS_UNSPECIFIED
}

func (x *WorkerError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WorkerError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *WorkerError) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

// ── Control signals ──────────────────────────────────────────────────────
type Pause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"` // schema mismatch pauses ONE table, not the whole worker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pause) Reset() {
	*x = Pause{}
	mi := &file_urutau_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pause) ProtoMessage() {}

func (x *Pause) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pause.ProtoReflect.Descriptor instead.
func (*Pause) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *Pause) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Pause) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type Shutdown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Grace *durationpb.Duration   `protobuf:"bytes,1,opt,name=grace,proto3" json:"grace,omitempty"`
	// true  → flush + commit + ack in-flight, exit 0 (graceful)
	// false → abort in-flight transactions, exit 1
	Drain         bool `protobuf:"varint,2,opt,name=drain,proto3" json:"drain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_urutau_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *Shutdown) GetGrace() *durationpb.Duration {
	if x != nil {
		return x.Grace
	}
	return nil
}

func (x *Shutdown) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

// ── Data plane ───────────────────────────────────────────────────────────
// The FlightData body is raw Arrow IPC; BatchMeta travels in
// FlightData.app_metadata.
type BatchMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"` // target table
	LowPos        string                 `protobuf:"bytes,2,opt,name=low_pos,json=lowPos,proto3" json:"low_pos,omitempty"`
	HighPos       string                 `protobuf:"bytes,3,opt,name=high_pos,json=highPos,proto3" json:"high_pos,omitempty"`
	BatchId       uint64                 `protobuf:"varint,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Epoch         uint64                 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"` // same guard as Ack
	Window        *WindowTag             `protobuf:"bytes,6,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMeta) Reset() {
	*x = BatchMeta{}
	mi := &file_urutau_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMeta) ProtoMessage() {}

func (x *BatchMeta) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMeta.ProtoReflect.Descriptor instead.
func (*BatchMeta) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *BatchMeta) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *BatchMeta) GetLowPos() string {
	if x != nil {
		return x.LowPos
	}
	return ""
}

func (x *BatchMeta) GetHighPos() string {
	if x != nil {
		return x.HighPos
	}
	return ""
}

func (x *BatchMeta) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *BatchMeta) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BatchMeta) GetWindow() *WindowTag {
	if x != nil {
		return x.Window
	}
	return nil
}

type WindowTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InWindow      bool                   `protobuf:"varint,1,opt,name=in_window,json=inWindow,proto3" json:"in_window,omitempty"`
	Closes        bool                   `protobuf:"varint,2,opt,name=closes,proto3" json:"closes,omitempty"`
	ChunkId       uint32                 `protobuf:"varint,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowTag) Reset() {
	*x = WindowTag{}
	mi := &file_urutau_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowTag) ProtoMessage() {}

func (x *WindowTag) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowTag.ProtoReflect.Descriptor instead.
func (*WindowTag) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *WindowTag) GetInWindow() bool {
	if x != nil {
		return x.InWindow
	}
	return false
}

func (x *WindowTag) GetCloses() bool {
	if x != nil {
		return x.Closes
	}
	return false
}

func (x *WindowTag) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

var File_urutau_v1_control_proto protoreflect.FileDescriptor

const file_urutau_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x17urutau/v1/control.proto\x12\turutau.v1\x1a\x1egoogle/protobuf/duration.proto\"\x8b\x02\n" +
	"\rWorkerMessage\x12(\n" +
	"\x05hello\x18\x01 \x01(\v2\x10.urutau.v1.HelloH\x00R\x05hello\x12\"\n" +
	"\x03ack\x18\x02 \x01(\v2\x0e.urutau.v1.AckH\x00R\x03ack\x128\n" +
	"\vchunk_ready\x18\x03 \x01(\v2\x15.urutau.v1.ChunkReadyH\x00R\n" +
	"chunkReady\x12;\n" +
	"\fchunk_failed\x18\x04 \x01(\v2\x16.urutau.v1.ChunkFailedH\x00R\vchunkFailed\x12.\n" +
	"\x05error\x18\x05 \x01(\v2\x16.urutau.v1.WorkerErrorH\x00R\x05errorB\x05\n" +
	"\x03msg\"}\n" +
	"\x12CoordinatorMessage\x12/\n" +
	"\x06assign\x18\x01 \x01(\v2\x15.urutau.v1.AssignmentH\x00R\x06assign\x12/\n" +
	"\x05chunk\x18\x02 \x01(\v2\x17.urutau.v1.ChunkRequestH\x00R\x05chunkB\x05\n" +
	"\x03msg\"t\n" +
	"\x0eControlMessage\x12(\n" +
	"\x05pause\x18\x01 \x01(\v2\x10.urutau.v1.PauseH\x00R\x05pause\x121\n" +
	"\bshutdown\x18\x02 \x01(\v2\x13.urutau.v1.ShutdownH\x00R\bshutdownB\x05\n" +
	"\x03msg\"\xd0\x03\n" +
	"\x05Hello\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12\x17\n" +
	"\apod_uid\x18\x02 \x01(\tR\x06podUid\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12,\n" +
	"\x05phase\x18\x04 \x01(\x0e2\x16.urutau.v1.WorkerPhaseR\x05phase\x12!\n" +
	"\fimage_digest\x18\x05 \x01(\tR\vimageDigest\x12=\n" +
	"\tcommitted\x18\x06 \x03(\v2\x1f.urutau.v1.Hello.CommittedEntryR\tcommitted\x12P\n" +
	"\x10completed_chunks\x18\a \x03(\v2%.urutau.v1.Hello.CompletedChunksEntryR\x0fcompletedChunks\x1a<\n" +
	"\x0eCommittedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aW\n" +
	"\x14CompletedChunksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.urutau.v1.ChunkIdsR\x05value:\x028\x01\"\x1c\n" +
	"\bChunkIds\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\rR\x03ids\"\xa8\x02\n" +
	"\x0fTableAssignment\x12!\n" +
	"\fsource_table\x18\x01 \x01(\tR\vsourceTable\x12!\n" +
	"\ftarget_table\x18\x02 \x01(\tR\vtargetTable\x123\n" +
	"\n" +
	"write_mode\x18\x03 \x01(\x0e2\x14.urutau.v1.WriteModeR\twriteMode\x12\x1f\n" +
	"\vprimary_key\x18\x04 \x03(\tR\n" +
	"primaryKey\x12!\n" +
	"\fpartition_by\x18\x05 \x03(\tR\vpartitionBy\x12%\n" +
	"\x0einclude_before\x18\x06 \x01(\bR\rincludeBefore\x12/\n" +
	"\x14create_if_not_exists\x18\a \x01(\bR\x11createIfNotExists\"h\n" +
	"\vBatchConfig\x12\x1b\n" +
	"\tmax_bytes\x18\x01 \x01(\x03R\bmaxBytes\x12<\n" +
	"\fmax_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vmaxInterval\"\xfb\x01\n" +
	"\n" +
	"Assignment\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x16\n" +
	"\x06ticket\x18\x04 \x01(\fR\x06ticket\x122\n" +
	"\x06tables\x18\x05 \x03(\v2\x1a.urutau.v1.TableAssignmentR\x06tables\x122\n" +
	"\bbatching\x18\x06 \x01(\v2\x16.urutau.v1.BatchConfigR\bbatching\x12\x1f\n" +
	"\vresume_from\x18\a \x01(\tR\n" +
	"resumeFrom\"\xda\x01\n" +
	"\x03Ack\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12\x12\n" +
	"\x04rows\x18\x05 \x01(\x04R\x04rows\x12\x18\n" +
	"\adeletes\x18\x06 \x01(\x04R\adeletes\x12B\n" +
	"\x0fcommit_duration\x18\a \x01(\v2\x19.google.protobuf.DurationR\x0ecommitDuration\"\x8c\x01\n" +
	"\fChunkRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\rR\achunkId\x12\x10\n" +
	"\x03low\x18\x03 \x01(\fR\x03low\x12\x12\n" +
	"\x04high\x18\x04 \x01(\fR\x04high\x12%\n" +
	"\x0einclusive_high\x18\x05 \x01(\bR\rinclusiveHigh\"}\n" +
	"\n" +
	"ChunkReady\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\rR\achunkId\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x04R\x04rows\x12*\n" +
	"\x11dropped_by_window\x18\x04 \x01(\x04R\x0fdroppedByWindow\"\x83\x01\n" +
	"\vChunkFailed\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\rR\achunkId\x12+\n" +
	"\x05class\x18\x03 \x01(\x0e2\x15.urutau.v1.ErrorClassR\x05class\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"|\n" +
	"\vWorkerError\x12+\n" +
	"\x05class\x18\x01 \x01(\x0e2\x15.urutau.v1.ErrorClassR\x05class\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x14\n" +
	"\x05table\x18\x04 \x01(\tR\x05table\"5\n" +
	"\x05Pause\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\"Q\n" +
	"\bShutdown\x12/\n" +
	"\x05grace\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05grace\x12\x14\n" +
	"\x05drain\x18\x02 \x01(\bR\x05drain\"\xb4\x01\n" +
	"\tBatchMeta\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x17\n" +
	"\alow_pos\x18\x02 \x01(\tR\x06lowPos\x12\x19\n" +
	"\bhigh_pos\x18\x03 \x01(\tR\ahighPos\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\x04R\abatchId\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x04R\x05epoch\x12,\n" +
	"\x06window\x18\x06 \x01(\v2\x14.urutau.v1.WindowTagR\x06window\"[\n" +
	"\tWindowTag\x12\x1b\n" +
	"\tin_window\x18\x01 \x01(\bR\binWindow\x12\x16\n" +
	"\x06closes\x18\x02 \x01(\bR\x06closes\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\rR\achunkId*\x81\x01\n" +
	"\vWorkerPhase\x12\x1c\n" +
	"\x18WORKER_PHASE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WORKER_PHASE_STARTING\x10\x01\x12\x1d\n" +
	"\x19WORKER_PHASE_SNAPSHOTTING\x10\x02\x12\x1a\n" +
	"\x16WORKER_PHASE_STREAMING\x10\x03*U\n" +
	"\tWriteMode\x12\x1a\n" +
	"\x16WRITE_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WRITE_MODE_UPSERT\x10\x01\x12\x15\n" +
	"\x11WRITE_MODE_APPEND\x10\x02*\x9a\x01\n" +
	"\n" +
	"ErrorClass\x12\x1b\n" +
	"\x17ERROR_CLASS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ERROR_CLASS_TRANSIENT\x10\x01\x12\x1c\n" +
	"\x18ERROR_CLASS_WORKER_FATAL\x10\x02\x12\x19\n" +
	"\x15ERROR_CLASS_JOB_FATAL\x10\x03\x12\x1b\n" +
	"\x17ERROR_CLASS_NEEDS_HUMAN\x10\x042\x9b\x01\n" +
	"\rUrutauControl\x12F\n" +
	"\aSession\x12\x18.urutau.v1.WorkerMessage\x1a\x1d.urutau.v1.CoordinatorMessage(\x010\x01\x12B\n" +
	"\aControl\x12\x18.urutau.v1.WorkerMessage\x1a\x19.urutau.v1.ControlMessage(\x010\x01B@Z>github.com/maltzsama/urutau/internal/transport/pb/urutau/v1;pbb\x06proto3"

var (
	file_urutau_v1_control_proto_rawDescOnce sync.Once
	file_urutau_v1_control_proto_rawDescData []byte
)

func file_urutau_v1_control_proto_rawDescGZIP() []byte {
	file_urutau_v1_control_proto_rawDescOnce.Do(func() {
		file_urutau_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_urutau_v1_control_proto_rawDesc), len(file_urutau_v1_control_proto_rawDesc)))
	})
	return file_urutau_v1_control_proto_rawDescData
}

var file_urutau_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_urutau_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_urutau_v1_control_proto_goTypes = []any{
	(WorkerPhase)(0),            // 0: urutau.v1.WorkerPhase
	(WriteMode)(0),              // 1: urutau.v1.WriteMode
	(ErrorClass)(0),             // 2: urutau.v1.ErrorClass
	(*WorkerMessage)(nil),       // 3: urutau.v1.WorkerMessage
	(*CoordinatorMessage)(nil),  // 4: urutau.v1.CoordinatorMessage
	(*ControlMessage)(nil),      // 5: urutau.v1.ControlMessage
	(*Hello)(nil),               // 6: urutau.v1.Hello
	(*ChunkIds)(nil),            // 7: urutau.v1.ChunkIds
	(*TableAssignment)(nil),     // 8: urutau.v1.TableAssignment
	(*BatchConfig)(nil),         // 9: urutau.v1.BatchConfig
	(*Assignment)(nil),          // 10: urutau.v1.Assignment
	(*Ack)(nil),                 // 11: urutau.v1.Ack
	(*ChunkRequest)(nil),        // 12: urutau.v1.ChunkRequest
	(*ChunkReady)(nil),          // 13: urutau.v1.ChunkReady
	(*ChunkFailed)(nil),         // 14: urutau.v1.ChunkFailed
	(*WorkerError)(nil),         // 15: urutau.v1.WorkerError
	(*Pause)(nil),               // 16: urutau.v1.Pause
	(*Shutdown)(nil),            // 17: urutau.v1.Shutdown
	(*BatchMeta)(nil),           // 18: urutau.v1.BatchMeta
	(*WindowTag)(nil),           // 19: urutau.v1.WindowTag
	nil,                         // 20: urutau.v1.Hello.CommittedEntry
	nil,                         // 21: urutau.v1.Hello.CompletedChunksEntry
	(*durationpb.Duration)(nil), // 22: google.protobuf.Duration
}
var file_urutau_v1_control_proto_depIdxs = []int32{
	6,  // 0: urutau.v1.WorkerMessage.hello:type_name -> urutau.v1.Hello
	11, // 1: urutau.v1.WorkerMessage.ack:type_name -> urutau.v1.Ack
	13, // 2: urutau.v1.WorkerMessage.chunk_ready:type_name -> urutau.v1.ChunkReady
	14, // 3: urutau.v1.WorkerMessage.chunk_failed:type_name -> urutau.v1.ChunkFailed
	15, // 4: urutau.v1.WorkerMessage.error:type_name -> urutau.v1.WorkerError
	10, // 5: urutau.v1.CoordinatorMessage.assign:type_name -> urutau.v1.Assignment
	12, // 6: urutau.v1.CoordinatorMessage.chunk:type_name -> urutau.v1.ChunkRequest
	16, // 7: urutau.v1.ControlMessage.pause:type_name -> urutau.v1.Pause
	17, // 8: urutau.v1.ControlMessage.shutdown:type_name -> urutau.v1.Shutdown
	0,  // 9: urutau.v1.Hello.phase:type_name -> urutau.v1.WorkerPhase
	20, // 10: urutau.v1.Hello.committed:type_name -> urutau.v1.Hello.CommittedEntry
	21, // 11: urutau.v1.Hello.completed_chunks:type_name -> urutau.v1.Hello.CompletedChunksEntry
	1,  // 12: urutau.v1.TableAssignment.write_mode:type_name -> urutau.v1.WriteMode
	22, // 13: urutau.v1.BatchConfig.max_interval:type_name -> google.protobuf.Duration
	8,  // 14: urutau.v1.Assignment.tables:type_name -> urutau.v1.TableAssignment
	9,  // 15: urutau.v1.Assignment.batching:type_name -> urutau.v1.BatchConfig
	22, // 16: urutau.v1.Ack.commit_duration:type_name -> google.protobuf.Duration
	2,  // 17: urutau.v1.ChunkFailed.class:type_name -> urutau.v1.ErrorClass
	2,  // 18: urutau.v1.WorkerError.class:type_name -> urutau.v1.ErrorClass
	22, // 19: urutau.v1.Shutdown.grace:type_name -> google.protobuf.Duration
	19, // 20: urutau.v1.BatchMeta.window:type_name -> urutau.v1.WindowTag
	7,  // 21: urutau.v1.Hello.CompletedChunksEntry.value:type_name -> urutau.v1.ChunkIds
	3,  // 22: urutau.v1.UrutauControl.Session:input_type -> urutau.v1.WorkerMessage
	3,  // 23: urutau.v1.UrutauControl.Control:input_type -> urutau.v1.WorkerMessage
	4,  // 24: urutau.v1.UrutauControl.Session:output_type -> urutau.v1.CoordinatorMessage
	5,  // 25: urutau.v1.UrutauControl.Control:output_type -> urutau.v1.ControlMessage
	24, // [24:26] is the sub-list for method output_type
	22, // [22:24] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_urutau_v1_control_proto_init() }
func file_urutau_v1_control_proto_init() {
	if File_urutau_v1_control_proto != nil {
		return
	}
	file_urutau_v1_control_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Ack)(nil),
		(*WorkerMessage_ChunkReady)(nil),
		(*WorkerMessage_ChunkFailed)(nil),
		(*WorkerMessage_Error)(nil),
	}
	file_urutau_v1_control_proto_msgTypes[1].OneofWrappers = []any{
		(*CoordinatorMessage_Assign)(nil),
		(*CoordinatorMessage_Chunk)(nil),
	}
	file_urutau_v1_control_proto_msgTypes[2].OneofWrappers = []any{
		(*ControlMessage_Pause)(nil),
		(*ControlMessage_Shutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_urutau_v1_control_proto_rawDesc), len(file_urutau_v1_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urutau_v1_control_proto_goTypes,
		DependencyIndexes: file_urutau_v1_control_proto_depIdxs,
		EnumInfos:         file_urutau_v1_control_proto_enumTypes,
		MessageInfos:      file_urutau_v1_control_proto_msgTypes,
	}.Build()
	File_urutau_v1_control_proto = out.File
	file_urutau_v1_control_proto_goTypes = nil
	file_urutau_v1_control_proto_depIdxs = nil
}
