// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: urutau/v1/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── Handshake ────────────────────────────────────────────────────────────
type WorkerPhase int32

const (
	WorkerPhase_WORKER_PHASE_UNSPECIFIED  WorkerPhase = 0
	WorkerPhase_WORKER_PHASE_STARTING     WorkerPhase = 1
	WorkerPhase_WORKER_PHASE_SNAPSHOTTING WorkerPhase = 2 // → coordinator re-issues pending chunks
	WorkerPhase_WORKER_PHASE_STREAMING    WorkerPhase = 3 // → coordinator opens an interval reader
)

// Enum value maps for WorkerPhase.
var (
	WorkerPhase_name = map[int32]string{
		0: "WORKER_PHASE_UNSPECIFIED",
		1: "WORKER_PHASE_STARTING",
		2: "WORKER_PHASE_SNAPSHOTTING",
		3: "WORKER_PHASE_STREAMING",
	}
	WorkerPhase_value = map[string]int32{
		"WORKER_PHASE_UNSPECIFIED":  0,
		"WORKER_PHASE_STARTING":     1,
		"WORKER_PHASE_SNAPSHOTTING": 2,
		"WORKER_PHASE_STREAMING":    3,
	}
)

func (x WorkerPhase) Enum() *WorkerPhase {
	p := new(WorkerPhase)
	*p = x
	return p
}

func (x WorkerPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_urutau_v1_control_proto_enumTypes[0].Descriptor()
}

func (WorkerPhase) Type() protoreflect.EnumType {
	return &file_urutau_v1_control_proto_enumTypes[0]
}

func (x WorkerPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerPhase.Descriptor instead.
func (WorkerPhase) EnumDescriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{0}
}

// ── Assignment ───────────────────────────────────────────────────────────
type WriteMode int32

const (
	WriteMode_WRITE_MODE_UNSPECIFIED WriteMode = 0
	WriteMode_WRITE_MODE_UPSERT      WriteMode = 1
	WriteMode_WRITE_MODE_APPEND      WriteMode = 2
)

// Enum value maps for WriteMode.
var (
	WriteMode_name = map[int32]string{
		0: "WRITE_MODE_UNSPECIFIED",
		1: "WRITE_MODE_UPSERT",
		2: "WRITE_MODE_APPEND",
	}
	WriteMode_value = map[string]int32{
		"WRITE_MODE_UNSPECIFIED": 0,
		"WRITE_MODE_UPSERT":      1,
		"WRITE_MODE_APPEND":      2,
	}
)

func (x WriteMode) Enum() *WriteMode {
	p := new(WriteMode)
	*p = x
	return p
}

func (x WriteMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteMode) Descriptor() protoreflect.EnumDescriptor {
	return file_urutau_v1_control_proto_enumTypes[1].Descriptor()
}

func (WriteMode) Type() protoreflect.EnumType {
	return &file_urutau_v1_control_proto_enumTypes[1]
}

func (x WriteMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteMode.Descriptor instead.
func (WriteMode) EnumDescriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{1}
}

// ── Errors ───────────────────────────────────────────────────────────────
type ErrorClass int32

const (
	ErrorClass_ERROR_CLASS_UNSPECIFIED  ErrorClass = 0
	ErrorClass_ERROR_CLASS_TRANSIENT    ErrorClass = 1 // retry with backoff
	ErrorClass_ERROR_CLASS_WORKER_FATAL ErrorClass = 2 // kill the worker → reset
	ErrorClass_ERROR_CLASS_JOB_FATAL    ErrorClass = 3 // terminal
	ErrorClass_ERROR_CLASS_NEEDS_HUMAN  ErrorClass = 4 // pause, wait for intervention
)

// Enum value maps for ErrorClass.
var (
	ErrorClass_name = map[int32]string{
		0: "ERROR_CLASS_UNSPECIFIED",
		1: "ERROR_CLASS_TRANSIENT",
		2: "ERROR_CLASS_WORKER_FATAL",
		3: "ERROR_CLASS_JOB_FATAL",
		4: "ERROR_CLASS_NEEDS_HUMAN",
	}
	ErrorClass_value = map[string]int32{
		"ERROR_CLASS_UNSPECIFIED":  0,
		"ERROR_CLASS_TRANSIENT":    1,
		"ERROR_CLASS_WORKER_FATAL": 2,
		"ERROR_CLASS_JOB_FATAL":    3,
		"ERROR_CLASS_NEEDS_HUMAN":  4,
	}
)

func (x ErrorClass) Enum() *ErrorClass {
	p := new(ErrorClass)
	*p = x
	return p
}

func (x ErrorClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorClass) Descriptor() protoreflect.EnumDescriptor {
	return file_urutau_v1_control_proto_enumTypes[2].Descriptor()
}

func (ErrorClass) Type() protoreflect.EnumType {
	return &file_urutau_v1_control_proto_enumTypes[2]
}

func (x ErrorClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorClass.Descriptor instead.
func (ErrorClass) EnumDescriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{2}
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Ack
	//	*WorkerMessage_ChunkReady
	//	*WorkerMessage_ChunkFailed
	//	*WorkerMessage_Error
	//	*WorkerMessage_Staged
	//	*WorkerMessage_MaintenanceResult
	//	*WorkerMessage_WorkerMetrics
	//	*WorkerMessage_SchemaDrift
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_urutau_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *WorkerMessage) GetChunkReady() *ChunkReady {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_ChunkReady); ok {
			return x.ChunkReady
		}
	}
	return nil
}

func (x *WorkerMessage) GetChunkFailed() *ChunkFailed {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_ChunkFailed); ok {
			return x.ChunkFailed
		}
	}
	return nil
}

func (x *WorkerMessage) GetError() *WorkerError {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *WorkerMessage) GetStaged() *StagedBatch {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Staged); ok {
			return x.Staged
		}
	}
	return nil
}

func (x *WorkerMessage) GetMaintenanceResult() *MaintenanceResult {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_MaintenanceResult); ok {
			return x.MaintenanceResult
		}
	}
	return nil
}

func (x *WorkerMessage) GetWorkerMetrics() *WorkerMetricsReport {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_WorkerMetrics); ok {
			return x.WorkerMetrics
		}
	}
	return nil
}

func (x *WorkerMessage) GetSchemaDrift() *SchemaDrift {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_SchemaDrift); ok {
			return x.SchemaDrift
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type WorkerMessage_ChunkReady struct {
	ChunkReady *ChunkReady `protobuf:"bytes,3,opt,name=chunk_ready,json=chunkReady,proto3,oneof"`
}

type WorkerMessage_ChunkFailed struct {
	ChunkFailed *ChunkFailed `protobuf:"bytes,4,opt,name=chunk_failed,json=chunkFailed,proto3,oneof"`
}

type WorkerMessage_Error struct {
	Error *WorkerError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type WorkerMessage_Staged struct {
	Staged *StagedBatch `protobuf:"bytes,6,opt,name=staged,proto3,oneof"` // staged data files, one per delivery (WK-001 C5)
}

type WorkerMessage_MaintenanceResult struct {
	MaintenanceResult *MaintenanceResult `protobuf:"bytes,7,opt,name=maintenance_result,json=maintenanceResult,proto3,oneof"` // one ephemeral maintenance pass's outcome
}

type WorkerMessage_WorkerMetrics struct {
	WorkerMetrics *WorkerMetricsReport `protobuf:"bytes,8,opt,name=worker_metrics,json=workerMetrics,proto3,oneof"` // periodic worker-side series the coordinator cannot derive from acks
}

type WorkerMessage_SchemaDrift struct {
	SchemaDrift *SchemaDrift `protobuf:"bytes,9,opt,name=schema_drift,json=schemaDrift,proto3,oneof"` // the worker detected schema drift and is stopping (issue #272)
}

func (*WorkerMessage_Hello) isWorkerMessage_Msg() {}

func (*WorkerMessage_Ack) isWorkerMessage_Msg() {}

func (*WorkerMessage_ChunkReady) isWorkerMessage_Msg() {}

func (*WorkerMessage_ChunkFailed) isWorkerMessage_Msg() {}

func (*WorkerMessage_Error) isWorkerMessage_Msg() {}

func (*WorkerMessage_Staged) isWorkerMessage_Msg() {}

func (*WorkerMessage_MaintenanceResult) isWorkerMessage_Msg() {}

func (*WorkerMessage_WorkerMetrics) isWorkerMessage_Msg() {}

func (*WorkerMessage_SchemaDrift) isWorkerMessage_Msg() {}

// SchemaDrift reports a column the source carries that the declared schema
// lacks; the worker fails after sending it, so the coordinator can surface the
// reason instead of a bare CrashLoopBackOff.
type SchemaDrift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Column        string                 `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // "added"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaDrift) Reset() {
	*x = SchemaDrift{}
	mi := &file_urutau_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaDrift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaDrift) ProtoMessage() {}

func (x *SchemaDrift) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaDrift.ProtoReflect.Descriptor instead.
func (*SchemaDrift) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *SchemaDrift) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SchemaDrift) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *SchemaDrift) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*CoordinatorMessage_Assign
	//	*CoordinatorMessage_Chunk
	//	*CoordinatorMessage_Maintenance
	Msg           isCoordinatorMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_urutau_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *CoordinatorMessage) GetMsg() isCoordinatorMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CoordinatorMessage) GetAssign() *Assignment {
	if x != nil {
		if x, ok := x.Msg.(*CoordinatorMessage_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetChunk() *ChunkRequest {
	if x != nil {
		if x, ok := x.Msg.(*CoordinatorMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetMaintenance() *MaintenanceAssignment {
	if x != nil {
		if x, ok := x.Msg.(*CoordinatorMessage_Maintenance); ok {
			return x.Maintenance
		}
	}
	return nil
}

type isCoordinatorMessage_Msg interface {
	isCoordinatorMessage_Msg()
}

type CoordinatorMessage_Assign struct {
	Assign *Assignment `protobuf:"bytes,1,opt,name=assign,proto3,oneof"`
}

type CoordinatorMessage_Chunk struct {
	Chunk *ChunkRequest `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type CoordinatorMessage_Maintenance struct {
	Maintenance *MaintenanceAssignment `protobuf:"bytes,3,opt,name=maintenance,proto3,oneof"`
}

func (*CoordinatorMessage_Assign) isCoordinatorMessage_Msg() {}

func (*CoordinatorMessage_Chunk) isCoordinatorMessage_Msg() {}

func (*CoordinatorMessage_Maintenance) isCoordinatorMessage_Msg() {}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControlMessage_Pause
	//	*ControlMessage_Shutdown
	Msg           isControlMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_urutau_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetMsg() isControlMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControlMessage) GetPause() *Pause {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *ControlMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isControlMessage_Msg interface {
	isControlMessage_Msg()
}

type ControlMessage_Pause struct {
	Pause *Pause `protobuf:"bytes,1,opt,name=pause,proto3,oneof"`
}

type ControlMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,2,opt,name=shutdown,proto3,oneof"`
}

func (*ControlMessage_Pause) isControlMessage_Msg() {}

func (*ControlMessage_Shutdown) isControlMessage_Msg() {}

type Hello struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkerName  string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	PodUid      string                 `protobuf:"bytes,2,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`                // detects zombies
	Epoch       uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`                               // bumped on every reset
	Phase       WorkerPhase            `protobuf:"varint,4,opt,name=phase,proto3,enum=urutau.v1.WorkerPhase" json:"phase,omitempty"`    // decides the recovery path
	ImageDigest string                 `protobuf:"bytes,5,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"` // detects image skew
	// target_table → committed position, read from the Iceberg table property.
	Committed map[string]string `protobuf:"bytes,6,rep,name=committed,proto3" json:"committed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Chunk ids already completed, per source table. Lets the coordinator
	// re-issue only what is pending after a mid-snapshot restart.
	CompletedChunks map[string]*ChunkIds `protobuf:"bytes,7,rep,name=completed_chunks,json=completedChunks,proto3" json:"completed_chunks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// maintenance marks an ephemeral maintenance worker: it runs ONE
	// maintenance pass for one table and exits. The coordinator answers with a
	// MaintenanceAssignment (never a data Assignment), and does not supervise
	// it for acks — it has no data plane.
	Maintenance   bool `protobuf:"varint,8,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_urutau_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Hello) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *Hello) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Hello) GetPhase() WorkerPhase {
	if x != nil {
		return x.Phase
	}
	return WorkerPhase_WORKER_PHASE_UNSPECIFIED
}

func (x *Hello) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *Hello) GetCommitted() map[string]string {
	if x != nil {
		return x.Committed
	}
	return nil
}

func (x *Hello) GetCompletedChunks() map[string]*ChunkIds {
	if x != nil {
		return x.CompletedChunks
	}
	return nil
}

func (x *Hello) GetMaintenance() bool {
	if x != nil {
		return x.Maintenance
	}
	return false
}

// MaintenanceAssignment is the maintenance worker's whole job: the table to
// maintain, the operations to run (in order), and the operation parameters.
// Intervals are NOT here: the coordinator already decided which operations
// are due.
type MaintenanceAssignment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetTable       string                 `protobuf:"bytes,1,opt,name=target_table,json=targetTable,proto3" json:"target_table,omitempty"`                   // "raw.orders"
	Ops               []string               `protobuf:"bytes,2,rep,name=ops,proto3" json:"ops,omitempty"`                                                      // "compaction", "snapshot_expiry", "orphan_cleanup"
	MaintenanceConfig []byte                 `protobuf:"bytes,3,opt,name=maintenance_config,json=maintenanceConfig,proto3" json:"maintenance_config,omitempty"` // JSON spec.Maintenance (parameters; intervals ignored)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MaintenanceAssignment) Reset() {
	*x = MaintenanceAssignment{}
	mi := &file_urutau_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceAssignment) ProtoMessage() {}

func (x *MaintenanceAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceAssignment.ProtoReflect.Descriptor instead.
func (*MaintenanceAssignment) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *MaintenanceAssignment) GetTargetTable() string {
	if x != nil {
		return x.TargetTable
	}
	return ""
}

func (x *MaintenanceAssignment) GetOps() []string {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *MaintenanceAssignment) GetMaintenanceConfig() []byte {
	if x != nil {
		return x.MaintenanceConfig
	}
	return nil
}

// MaintenanceResult is what an ephemeral maintenance worker reports after a
// pass: one entry per operation that actually ran, in execution order, with
// raw counts and the error (empty on success). The coordinator records them
// in its own long-lived registry — the worker's own /metrics dies with the
// worker, so this is what makes the counts survive to a scrape.
type MaintenanceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*MaintenanceOpResult `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceResult) Reset() {
	*x = MaintenanceResult{}
	mi := &file_urutau_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceResult) ProtoMessage() {}

func (x *MaintenanceResult) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceResult.ProtoReflect.Descriptor instead.
func (*MaintenanceResult) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *MaintenanceResult) GetOps() []*MaintenanceOpResult {
	if x != nil {
		return x.Ops
	}
	return nil
}

type MaintenanceOpResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*MaintenanceOpResult_Compaction
	//	*MaintenanceOpResult_Expiry
	//	*MaintenanceOpResult_Orphan
	Op            isMaintenanceOpResult_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceOpResult) Reset() {
	*x = MaintenanceOpResult{}
	mi := &file_urutau_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceOpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceOpResult) ProtoMessage() {}

func (x *MaintenanceOpResult) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceOpResult.ProtoReflect.Descriptor instead.
func (*MaintenanceOpResult) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *MaintenanceOpResult) GetOp() isMaintenanceOpResult_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *MaintenanceOpResult) GetCompaction() *CompactionResult {
	if x != nil {
		if x, ok := x.Op.(*MaintenanceOpResult_Compaction); ok {
			return x.Compaction
		}
	}
	return nil
}

func (x *MaintenanceOpResult) GetExpiry() *ExpiryResult {
	if x != nil {
		if x, ok := x.Op.(*MaintenanceOpResult_Expiry); ok {
			return x.Expiry
		}
	}
	return nil
}

func (x *MaintenanceOpResult) GetOrphan() *OrphanResult {
	if x != nil {
		if x, ok := x.Op.(*MaintenanceOpResult_Orphan); ok {
			return x.Orphan
		}
	}
	return nil
}

type isMaintenanceOpResult_Op interface {
	isMaintenanceOpResult_Op()
}

type MaintenanceOpResult_Compaction struct {
	Compaction *CompactionResult `protobuf:"bytes,1,opt,name=compaction,proto3,oneof"`
}

type MaintenanceOpResult_Expiry struct {
	Expiry *ExpiryResult `protobuf:"bytes,2,opt,name=expiry,proto3,oneof"`
}

type MaintenanceOpResult_Orphan struct {
	Orphan *OrphanResult `protobuf:"bytes,3,opt,name=orphan,proto3,oneof"`
}

func (*MaintenanceOpResult_Compaction) isMaintenanceOpResult_Op() {}

func (*MaintenanceOpResult_Expiry) isMaintenanceOpResult_Op() {}

func (*MaintenanceOpResult_Orphan) isMaintenanceOpResult_Op() {}

type CompactionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesRemoved  int64                  `protobuf:"varint,1,opt,name=files_removed,json=filesRemoved,proto3" json:"files_removed,omitempty"`
	FilesAdded    int64                  `protobuf:"varint,2,opt,name=files_added,json=filesAdded,proto3" json:"files_added,omitempty"`
	BytesBefore   int64                  `protobuf:"varint,3,opt,name=bytes_before,json=bytesBefore,proto3" json:"bytes_before,omitempty"`
	BytesAfter    int64                  `protobuf:"varint,4,opt,name=bytes_after,json=bytesAfter,proto3" json:"bytes_after,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactionResult) Reset() {
	*x = CompactionResult{}
	mi := &file_urutau_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactionResult) ProtoMessage() {}

func (x *CompactionResult) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactionResult.ProtoReflect.Descriptor instead.
func (*CompactionResult) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *CompactionResult) GetFilesRemoved() int64 {
	if x != nil {
		return x.FilesRemoved
	}
	return 0
}

func (x *CompactionResult) GetFilesAdded() int64 {
	if x != nil {
		return x.FilesAdded
	}
	return 0
}

func (x *CompactionResult) GetBytesBefore() int64 {
	if x != nil {
		return x.BytesBefore
	}
	return 0
}

func (x *CompactionResult) GetBytesAfter() int64 {
	if x != nil {
		return x.BytesAfter
	}
	return 0
}

func (x *CompactionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExpiryResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SnapshotsRemoved int64                  `protobuf:"varint,1,opt,name=snapshots_removed,json=snapshotsRemoved,proto3" json:"snapshots_removed,omitempty"`
	Error            string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExpiryResult) Reset() {
	*x = ExpiryResult{}
	mi := &file_urutau_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpiryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpiryResult) ProtoMessage() {}

func (x *ExpiryResult) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpiryResult.ProtoReflect.Descriptor instead.
func (*ExpiryResult) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ExpiryResult) GetSnapshotsRemoved() int64 {
	if x != nil {
		return x.SnapshotsRemoved
	}
	return 0
}

func (x *ExpiryResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OrphanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesDeleted  int64                  `protobuf:"varint,1,opt,name=files_deleted,json=filesDeleted,proto3" json:"files_deleted,omitempty"`
	BytesFreed    int64                  `protobuf:"varint,2,opt,name=bytes_freed,json=bytesFreed,proto3" json:"bytes_freed,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrphanResult) Reset() {
	*x = OrphanResult{}
	mi := &file_urutau_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrphanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrphanResult) ProtoMessage() {}

func (x *OrphanResult) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrphanResult.ProtoReflect.Descriptor instead.
func (*OrphanResult) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *OrphanResult) GetFilesDeleted() int64 {
	if x != nil {
		return x.FilesDeleted
	}
	return 0
}

func (x *OrphanResult) GetBytesFreed() int64 {
	if x != nil {
		return x.BytesFreed
	}
	return 0
}

func (x *OrphanResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// WorkerMetricsReport is the worker's periodic report of the series the
// coordinator cannot derive from acks: commit failures, dropped deletes,
// snapshot progress, and enrich counters. Per-table (and per-reference for
// enrich), so the coordinator can label its own registry. Counters are
// cumulative totals, not deltas.
type WorkerMetricsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*TableMetrics        `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMetricsReport) Reset() {
	*x = WorkerMetricsReport{}
	mi := &file_urutau_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMetricsReport) ProtoMessage() {}

func (x *WorkerMetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMetricsReport.ProtoReflect.Descriptor instead.
func (*WorkerMetricsReport) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *WorkerMetricsReport) GetTables() []*TableMetrics {
	if x != nil {
		return x.Tables
	}
	return nil
}

type TableMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Table            string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	CommitFailures   int64                  `protobuf:"varint,2,opt,name=commit_failures,json=commitFailures,proto3" json:"commit_failures,omitempty"`
	DeletesDropped   int64                  `protobuf:"varint,3,opt,name=deletes_dropped,json=deletesDropped,proto3" json:"deletes_dropped,omitempty"`
	SnapshotProgress float64                `protobuf:"fixed64,4,opt,name=snapshot_progress,json=snapshotProgress,proto3" json:"snapshot_progress,omitempty"`
	Enrich           []*EnrichMetrics       `protobuf:"bytes,5,rep,name=enrich,proto3" json:"enrich,omitempty"`
	CommitLatencyMs  float64                `protobuf:"fixed64,6,opt,name=commit_latency_ms,json=commitLatencyMs,proto3" json:"commit_latency_ms,omitempty"` // last Iceberg commit latency, per table
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TableMetrics) Reset() {
	*x = TableMetrics{}
	mi := &file_urutau_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableMetrics) ProtoMessage() {}

func (x *TableMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableMetrics.ProtoReflect.Descriptor instead.
func (*TableMetrics) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *TableMetrics) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *TableMetrics) GetCommitFailures() int64 {
	if x != nil {
		return x.CommitFailures
	}
	return 0
}

func (x *TableMetrics) GetDeletesDropped() int64 {
	if x != nil {
		return x.DeletesDropped
	}
	return 0
}

func (x *TableMetrics) GetSnapshotProgress() float64 {
	if x != nil {
		return x.SnapshotProgress
	}
	return 0
}

func (x *TableMetrics) GetEnrich() []*EnrichMetrics {
	if x != nil {
		return x.Enrich
	}
	return nil
}

func (x *TableMetrics) GetCommitLatencyMs() float64 {
	if x != nil {
		return x.CommitLatencyMs
	}
	return 0
}

type EnrichMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Misses        int64                  `protobuf:"varint,2,opt,name=misses,proto3" json:"misses,omitempty"`
	InnerDropped  int64                  `protobuf:"varint,3,opt,name=inner_dropped,json=innerDropped,proto3" json:"inner_dropped,omitempty"`
	Evicted       int64                  `protobuf:"varint,4,opt,name=evicted,proto3" json:"evicted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichMetrics) Reset() {
	*x = EnrichMetrics{}
	mi := &file_urutau_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichMetrics) ProtoMessage() {}

func (x *EnrichMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichMetrics.ProtoReflect.Descriptor instead.
func (*EnrichMetrics) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *EnrichMetrics) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *EnrichMetrics) GetMisses() int64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *EnrichMetrics) GetInnerDropped() int64 {
	if x != nil {
		return x.InnerDropped
	}
	return 0
}

func (x *EnrichMetrics) GetEvicted() int64 {
	if x != nil {
		return x.Evicted
	}
	return 0
}

type ChunkIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint32               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkIds) Reset() {
	*x = ChunkIds{}
	mi := &file_urutau_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkIds) ProtoMessage() {}

func (x *ChunkIds) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkIds.ProtoReflect.Descriptor instead.
func (*ChunkIds) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *ChunkIds) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// EnrichRef is one broadcast reference join the worker applies to the
// table's events: the reference is read whole into the worker's RAM and
// re-read on the refresh interval. The coordinator owns the spec; the
// worker owns the join.
type EnrichRef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Table           string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`                                                                     // reference name (diagnostics)
	SourceUri       string                 `protobuf:"bytes,2,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`                                            // reference connection (mysql:// | postgres://)
	SourceQuery     string                 `protobuf:"bytes,3,opt,name=source_query,json=sourceQuery,proto3" json:"source_query,omitempty"`                                      // full reference image SELECT
	On              map[string]string      `protobuf:"bytes,4,rep,name=on,proto3" json:"on,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // event column → reference column
	Select          []string               `protobuf:"bytes,5,rep,name=select,proto3" json:"select,omitempty"`                                                                   // required: reference columns to inject ("*" = all except join key)
	As              map[string]string      `protobuf:"bytes,6,rep,name=as,proto3" json:"as,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // reference column → destination name
	JoinType        string                 `protobuf:"bytes,7,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"`                                               // left | inner
	Refresh         string                 `protobuf:"bytes,8,opt,name=refresh,proto3" json:"refresh,omitempty"`                                                                 // duration; empty = worker default (5m)
	OnColdStart     string                 `protobuf:"bytes,9,opt,name=on_cold_start,json=onColdStart,proto3" json:"on_cold_start,omitempty"`                                    // buffer | pass | drop (empty = buffer)
	BufferMaxEvents int64                  `protobuf:"varint,10,opt,name=buffer_max_events,json=bufferMaxEvents,proto3" json:"buffer_max_events,omitempty"`
	BufferMaxWait   string                 `protobuf:"bytes,11,opt,name=buffer_max_wait,json=bufferMaxWait,proto3" json:"buffer_max_wait,omitempty"` // duration; empty = unbounded
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrichRef) Reset() {
	*x = EnrichRef{}
	mi := &file_urutau_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichRef) ProtoMessage() {}

func (x *EnrichRef) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichRef.ProtoReflect.Descriptor instead.
func (*EnrichRef) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *EnrichRef) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *EnrichRef) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *EnrichRef) GetSourceQuery() string {
	if x != nil {
		return x.SourceQuery
	}
	return ""
}

func (x *EnrichRef) GetOn() map[string]string {
	if x != nil {
		return x.On
	}
	return nil
}

func (x *EnrichRef) GetSelect() []string {
	if x != nil {
		return x.Select
	}
	return nil
}

func (x *EnrichRef) GetAs() map[string]string {
	if x != nil {
		return x.As
	}
	return nil
}

func (x *EnrichRef) GetJoinType() string {
	if x != nil {
		return x.JoinType
	}
	return ""
}

func (x *EnrichRef) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

func (x *EnrichRef) GetOnColdStart() string {
	if x != nil {
		return x.OnColdStart
	}
	return ""
}

func (x *EnrichRef) GetBufferMaxEvents() int64 {
	if x != nil {
		return x.BufferMaxEvents
	}
	return 0
}

func (x *EnrichRef) GetBufferMaxWait() string {
	if x != nil {
		return x.BufferMaxWait
	}
	return ""
}

type TableAssignment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SourceTable       string                 `protobuf:"bytes,1,opt,name=source_table,json=sourceTable,proto3" json:"source_table,omitempty"` // "shop.orders"
	TargetTable       string                 `protobuf:"bytes,2,opt,name=target_table,json=targetTable,proto3" json:"target_table,omitempty"` // "lakehouse.orders"
	WriteMode         WriteMode              `protobuf:"varint,3,opt,name=write_mode,json=writeMode,proto3,enum=urutau.v1.WriteMode" json:"write_mode,omitempty"`
	PrimaryKey        []string               `protobuf:"bytes,4,rep,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`           // equality-delete key; required on upsert
	PartitionBy       []string               `protobuf:"bytes,5,rep,name=partition_by,json=partitionBy,proto3" json:"partition_by,omitempty"`        // native Iceberg transforms
	IncludeBefore     bool                   `protobuf:"varint,6,opt,name=include_before,json=includeBefore,proto3" json:"include_before,omitempty"` // derived: true only with a mutable-column filter
	CreateIfNotExists bool                   `protobuf:"varint,7,opt,name=create_if_not_exists,json=createIfNotExists,proto3" json:"create_if_not_exists,omitempty"`
	SchemaArrow       []byte                 `protobuf:"bytes,8,opt,name=schema_arrow,json=schemaArrow,proto3" json:"schema_arrow,omitempty"`     // table schema as Arrow IPC (data columns); the coordinator owns introspection
	Enrich            []*EnrichRef           `protobuf:"bytes,9,rep,name=enrich,proto3" json:"enrich,omitempty"`                                  // broadcast reference joins, applied in order
	CastPolicy        []byte                 `protobuf:"bytes,10,opt,name=cast_policy,json=castPolicy,proto3" json:"cast_policy,omitempty"`       // JSON core.CastPolicy — writes must apply the same overrides as the coordinator's DDL
	Metadata          []byte                 `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`                             // JSON []core.MetadataColumn — pipeline metadata columns land in the target
	Staged            bool                   `protobuf:"varint,12,opt,name=staged,proto3" json:"staged,omitempty"`                                // workers>1 on a staging sink: stage data files, let the coordinator commit the cycle (WK-001 C5.5)
	ColumnFilter      []string               `protobuf:"bytes,13,rep,name=column_filter,json=columnFilter,proto3" json:"column_filter,omitempty"` // source column projection (#162): the snapshot SELECT list
	Filter            []byte                 `protobuf:"bytes,14,opt,name=filter,proto3" json:"filter,omitempty"`                                 // JSON spec.Filter (#163): the source WHERE predicate, composed with the chunk bounds
	ChunkColumn       string                 `protobuf:"bytes,15,opt,name=chunk_column,json=chunkColumn,proto3" json:"chunk_column,omitempty"`    // snapshot chunking column (#151); empty = the source's default (Postgres CTID)
	OnDelete          string                 `protobuf:"bytes,16,opt,name=on_delete,json=onDelete,proto3" json:"on_delete,omitempty"`             // spec.OnDelete ("skip" | "record" | ""); append-only delete handling (issue #264)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TableAssignment) Reset() {
	*x = TableAssignment{}
	mi := &file_urutau_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableAssignment) ProtoMessage() {}

func (x *TableAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableAssignment.ProtoReflect.Descriptor instead.
func (*TableAssignment) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *TableAssignment) GetSourceTable() string {
	if x != nil {
		return x.SourceTable
	}
	return ""
}

func (x *TableAssignment) GetTargetTable() string {
	if x != nil {
		return x.TargetTable
	}
	return ""
}

func (x *TableAssignment) GetWriteMode() WriteMode {
	if x != nil {
		return x.WriteMode
	}
	return WriteMode_WRITE_MODE_UNSPECIFIED
}

func (x *TableAssignment) GetPrimaryKey() []string {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *TableAssignment) GetPartitionBy() []string {
	if x != nil {
		return x.PartitionBy
	}
	return nil
}

func (x *TableAssignment) GetIncludeBefore() bool {
	if x != nil {
		return x.IncludeBefore
	}
	return false
}

func (x *TableAssignment) GetCreateIfNotExists() bool {
	if x != nil {
		return x.CreateIfNotExists
	}
	return false
}

func (x *TableAssignment) GetSchemaArrow() []byte {
	if x != nil {
		return x.SchemaArrow
	}
	return nil
}

func (x *TableAssignment) GetEnrich() []*EnrichRef {
	if x != nil {
		return x.Enrich
	}
	return nil
}

func (x *TableAssignment) GetCastPolicy() []byte {
	if x != nil {
		return x.CastPolicy
	}
	return nil
}

func (x *TableAssignment) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TableAssignment) GetStaged() bool {
	if x != nil {
		return x.Staged
	}
	return false
}

func (x *TableAssignment) GetColumnFilter() []string {
	if x != nil {
		return x.ColumnFilter
	}
	return nil
}

func (x *TableAssignment) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *TableAssignment) GetChunkColumn() string {
	if x != nil {
		return x.ChunkColumn
	}
	return ""
}

func (x *TableAssignment) GetOnDelete() string {
	if x != nil {
		return x.OnDelete
	}
	return ""
}

type BatchConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxBytes      int64                  `protobuf:"varint,1,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	MaxInterval   *durationpb.Duration   `protobuf:"bytes,2,opt,name=max_interval,json=maxInterval,proto3" json:"max_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchConfig) Reset() {
	*x = BatchConfig{}
	mi := &file_urutau_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchConfig) ProtoMessage() {}

func (x *BatchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchConfig.ProtoReflect.Descriptor instead.
func (*BatchConfig) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *BatchConfig) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *BatchConfig) GetMaxInterval() *durationpb.Duration {
	if x != nil {
		return x.MaxInterval
	}
	return nil
}

type Assignment struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	WorkerName string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	Epoch      uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	RunId      string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Ticket     []byte                 `protobuf:"bytes,4,opt,name=ticket,proto3" json:"ticket,omitempty"` // Flight DoGet ticket
	Tables     []*TableAssignment     `protobuf:"bytes,5,rep,name=tables,proto3" json:"tables,omitempty"`
	Batching   *BatchConfig           `protobuf:"bytes,6,opt,name=batching,proto3" json:"batching,omitempty"`                       // already resolved, including worker override
	ResumeFrom string                 `protobuf:"bytes,7,opt,name=resume_from,json=resumeFrom,proto3" json:"resume_from,omitempty"` // min() position this worker resumes from
	SourceKind string                 `protobuf:"bytes,8,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"` // "mysql" | "postgres" — how to parse positions
	SourceDsn  string                 `protobuf:"bytes,9,opt,name=source_dsn,json=sourceDsn,proto3" json:"source_dsn,omitempty"`    // query connection for snapshot chunk SELECTs
	ChunkSize  uint32                 `protobuf:"varint,10,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`  // DBLog chunk granularity for chunk SELECTs
	// postgres is the JSON spec.PostgresSource the worker rebuilds its snapshot
	// query source from, needed when the DSN alone cannot express the config —
	// an SSH tunnel has a DialFunc, not a DSN. Empty means "use source_dsn"
	// (a URI source, or a scoped read-only snapshotUri).
	Postgres      []byte `protobuf:"bytes,11,opt,name=postgres,proto3" json:"postgres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_urutau_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *Assignment) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Assignment) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Assignment) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Assignment) GetTicket() []byte {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *Assignment) GetTables() []*TableAssignment {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *Assignment) GetBatching() *BatchConfig {
	if x != nil {
		return x.Batching
	}
	return nil
}

func (x *Assignment) GetResumeFrom() string {
	if x != nil {
		return x.ResumeFrom
	}
	return ""
}

func (x *Assignment) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *Assignment) GetSourceDsn() string {
	if x != nil {
		return x.SourceDsn
	}
	return ""
}

func (x *Assignment) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *Assignment) GetPostgres() []byte {
	if x != nil {
		return x.Postgres
	}
	return nil
}

// ── Acks ─────────────────────────────────────────────────────────────────
type Ack struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchId        uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Epoch          uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`      // stale-epoch acks are rejected
	Table          string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`       // target table
	Position       string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"` // position AFTER the Iceberg commit
	Rows           uint64                 `protobuf:"varint,5,opt,name=rows,proto3" json:"rows,omitempty"`
	Deletes        uint64                 `protobuf:"varint,6,opt,name=deletes,proto3" json:"deletes,omitempty"` // equality deletes written — feeds collapse_ratio
	CommitDuration *durationpb.Duration   `protobuf:"bytes,7,opt,name=commit_duration,json=commitDuration,proto3" json:"commit_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_urutau_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *Ack) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *Ack) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Ack) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Ack) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Ack) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Ack) GetDeletes() uint64 {
	if x != nil {
		return x.Deletes
	}
	return 0
}

func (x *Ack) GetCommitDuration() *durationpb.Duration {
	if x != nil {
		return x.CommitDuration
	}
	return nil
}

// ── DBLog chunks ─────────────────────────────────────────────────────────
type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"` // source table
	ChunkId       uint32                 `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Bounds        []byte                 `protobuf:"bytes,3,opt,name=bounds,proto3" json:"bounds,omitempty"`                                     // Arrow IPC record: row 0 = low, row 1 = high (absent = open high)
	InclusiveHigh bool                   `protobuf:"varint,4,opt,name=inclusive_high,json=inclusiveHigh,proto3" json:"inclusive_high,omitempty"` // true only on the last chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_urutau_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *ChunkRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ChunkRequest) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *ChunkRequest) GetBounds() []byte {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *ChunkRequest) GetInclusiveHigh() bool {
	if x != nil {
		return x.InclusiveHigh
	}
	return false
}

type ChunkReady struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Table           string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"` // disambiguates parallel chunks
	ChunkId         uint32                 `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Rows            uint64                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	DroppedByWindow uint64                 `protobuf:"varint,4,opt,name=dropped_by_window,json=droppedByWindow,proto3" json:"dropped_by_window,omitempty"` // proves DBLog is working
	Epoch           uint64                 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`                                              // the Assignment epoch this reply belongs to; stale-epoch replies are ignored
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChunkReady) Reset() {
	*x = ChunkReady{}
	mi := &file_urutau_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkReady) ProtoMessage() {}

func (x *ChunkReady) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkReady.ProtoReflect.Descriptor instead.
func (*ChunkReady) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{21}
}

func (x *ChunkReady) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ChunkReady) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *ChunkReady) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ChunkReady) GetDroppedByWindow() uint64 {
	if x != nil {
		return x.DroppedByWindow
	}
	return 0
}

func (x *ChunkReady) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type ChunkFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	ChunkId       uint32                 `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Class         ErrorClass             `protobuf:"varint,3,opt,name=class,proto3,enum=urutau.v1.ErrorClass" json:"class,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkFailed) Reset() {
	*x = ChunkFailed{}
	mi := &file_urutau_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkFailed) ProtoMessage() {}

func (x *ChunkFailed) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkFailed.ProtoReflect.Descriptor instead.
func (*ChunkFailed) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *ChunkFailed) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ChunkFailed) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *ChunkFailed) GetClass() ErrorClass {
	if x != nil {
		return x.Class
	}
	return ErrorClass_ERROR_CLASS_UNSPECIFIED
}

func (x *ChunkFailed) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// ── Staged commits (WK-001 C5) ───────────────────────────────────────────
// A worker of a partitioned table writes its parquet data files and sends
// the opaque descriptor here instead of committing; the coordinator
// aggregates every delivery of one binlog batch (a cycle) and commits it
// once via StagedCommitter. Carries no data — only the descriptor and the
// batch metadata needed to close the cycle.
type StagedBatch struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Table           string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`                                                    // target table
	Seq             uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                                       // BatchMeta.batch_id — the cycle key
	Descriptor_     []byte                 `protobuf:"bytes,3,opt,name=descriptor,proto3" json:"descriptor,omitempty"`                                          // opaque payload from WriteStaged (DataFile codec)
	Position        string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`                                              // the batch's high position (watermark)
	SnapshotState   string                 `protobuf:"bytes,5,opt,name=snapshot_state,json=snapshotState,proto3" json:"snapshot_state,omitempty"`               // resumable-backfill state ("" when not in snapshot)
	SnapshotPending []uint32               `protobuf:"varint,6,rep,packed,name=snapshot_pending,json=snapshotPending,proto3" json:"snapshot_pending,omitempty"` // chunk ids still to process
	Epoch           uint64                 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`                                                   // stale-epoch guards, like Ack
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StagedBatch) Reset() {
	*x = StagedBatch{}
	mi := &file_urutau_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedBatch) ProtoMessage() {}

func (x *StagedBatch) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedBatch.ProtoReflect.Descriptor instead.
func (*StagedBatch) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{23}
}

func (x *StagedBatch) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *StagedBatch) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StagedBatch) GetDescriptor_() []byte {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *StagedBatch) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *StagedBatch) GetSnapshotState() string {
	if x != nil {
		return x.SnapshotState
	}
	return ""
}

func (x *StagedBatch) GetSnapshotPending() []uint32 {
	if x != nil {
		return x.SnapshotPending
	}
	return nil
}

func (x *StagedBatch) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type WorkerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         ErrorClass             `protobuf:"varint,1,opt,name=class,proto3,enum=urutau.v1.ErrorClass" json:"class,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"` // stable machine-readable id, e.g. "commit_exhausted"
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Table         string                 `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerError) Reset() {
	*x = WorkerError{}
	mi := &file_urutau_v1_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerError) ProtoMessage() {}

func (x *WorkerError) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerError.ProtoReflect.Descriptor instead.
func (*WorkerError) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{24}
}

func (x *WorkerError) GetClass() ErrorClass {
	if x != nil {
		return x.Class
	}
	return ErrorClass_ERROR_CLASS_UNSPECIFIED
}

func (x *WorkerError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WorkerError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *WorkerError) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

// ── Control signals ──────────────────────────────────────────────────────
type Pause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"` // schema mismatch pauses ONE table, not the whole worker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pause) Reset() {
	*x = Pause{}
	mi := &file_urutau_v1_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pause) ProtoMessage() {}

func (x *Pause) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pause.ProtoReflect.Descriptor instead.
func (*Pause) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{25}
}

func (x *Pause) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Pause) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type Shutdown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Grace *durationpb.Duration   `protobuf:"bytes,1,opt,name=grace,proto3" json:"grace,omitempty"`
	// true  → flush + commit + ack in-flight, exit 0 (graceful)
	// false → abort in-flight transactions, exit 1
	Drain         bool `protobuf:"varint,2,opt,name=drain,proto3" json:"drain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_urutau_v1_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{26}
}

func (x *Shutdown) GetGrace() *durationpb.Duration {
	if x != nil {
		return x.Grace
	}
	return nil
}

func (x *Shutdown) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

// ── Data plane ───────────────────────────────────────────────────────────
// The FlightData body is raw Arrow IPC; BatchMeta travels in
// FlightData.app_metadata.
type BatchMeta struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Table   string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"` // target table
	LowPos  string                 `protobuf:"bytes,2,opt,name=low_pos,json=lowPos,proto3" json:"low_pos,omitempty"`
	HighPos string                 `protobuf:"bytes,3,opt,name=high_pos,json=highPos,proto3" json:"high_pos,omitempty"`
	BatchId uint64                 `protobuf:"varint,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Epoch   uint64                 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"` // same guard as Ack
	Window  *WindowTag             `protobuf:"bytes,6,opt,name=window,proto3" json:"window,omitempty"`
	// staged tells the worker to stage this batch (write files, ship the
	// descriptor, let the coordinator commit the cycle) instead of committing
	// it directly. The coordinator decides per batch, so a table that changes
	// commit mode on a re-slice (1 owner → N) is consistent from the first
	// batch after the flip: the surviving owner stages too, and its cycle is
	// not left open blocking the new owners' cycles.
	Staged        bool `protobuf:"varint,7,opt,name=staged,proto3" json:"staged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMeta) Reset() {
	*x = BatchMeta{}
	mi := &file_urutau_v1_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMeta) ProtoMessage() {}

func (x *BatchMeta) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMeta.ProtoReflect.Descriptor instead.
func (*BatchMeta) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{27}
}

func (x *BatchMeta) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *BatchMeta) GetLowPos() string {
	if x != nil {
		return x.LowPos
	}
	return ""
}

func (x *BatchMeta) GetHighPos() string {
	if x != nil {
		return x.HighPos
	}
	return ""
}

func (x *BatchMeta) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *BatchMeta) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BatchMeta) GetWindow() *WindowTag {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *BatchMeta) GetStaged() bool {
	if x != nil {
		return x.Staged
	}
	return false
}

type WindowTag struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	InWindow bool                   `protobuf:"varint,1,opt,name=in_window,json=inWindow,proto3" json:"in_window,omitempty"`
	Closes   bool                   `protobuf:"varint,2,opt,name=closes,proto3" json:"closes,omitempty"`
	ChunkId  uint32                 `protobuf:"varint,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Snapshot bool                   `protobuf:"varint,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"` // true → rows feed AddWindowRows, not the ingest path
	// The table's snapshot is over: every window was sent ahead of this marker.
	// The worker commits cdc.snapshot.state=complete after them (issue #428).
	SnapshotDone  bool `protobuf:"varint,5,opt,name=snapshot_done,json=snapshotDone,proto3" json:"snapshot_done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowTag) Reset() {
	*x = WindowTag{}
	mi := &file_urutau_v1_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowTag) ProtoMessage() {}

func (x *WindowTag) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowTag.ProtoReflect.Descriptor instead.
func (*WindowTag) Descriptor() ([]byte, []int) {
	return file_urutau_v1_control_proto_rawDescGZIP(), []int{28}
}

func (x *WindowTag) GetInWindow() bool {
	if x != nil {
		return x.InWindow
	}
	return false
}

func (x *WindowTag) GetCloses() bool {
	if x != nil {
		return x.Closes
	}
	return false
}

func (x *WindowTag) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *WindowTag) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *WindowTag) GetSnapshotDone() bool {
	if x != nil {
		return x.SnapshotDone
	}
	return false
}

var File_urutau_v1_control_proto protoreflect.FileDescriptor

const file_urutau_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x17urutau/v1/control.proto\x12\turutau.v1\x1a\x1egoogle/protobuf/duration.proto\"\x92\x04\n" +
	"\rWorkerMessage\x12(\n" +
	"\x05hello\x18\x01 \x01(\v2\x10.urutau.v1.HelloH\x00R\x05hello\x12\"\n" +
	"\x03ack\x18\x02 \x01(\v2\x0e.urutau.v1.AckH\x00R\x03ack\x128\n" +
	"\vchunk_ready\x18\x03 \x01(\v2\x15.urutau.v1.ChunkReadyH\x00R\n" +
	"chunkReady\x12;\n" +
	"\fchunk_failed\x18\x04 \x01(\v2\x16.urutau.v1.ChunkFailedH\x00R\vchunkFailed\x12.\n" +
	"\x05error\x18\x05 \x01(\v2\x16.urutau.v1.WorkerErrorH\x00R\x05error\x120\n" +
	"\x06staged\x18\x06 \x01(\v2\x16.urutau.v1.StagedBatchH\x00R\x06staged\x12M\n" +
	"\x12maintenance_result\x18\a \x01(\v2\x1c.urutau.v1.MaintenanceResultH\x00R\x11maintenanceResult\x12G\n" +
	"\x0eworker_metrics\x18\b \x01(\v2\x1e.urutau.v1.WorkerMetricsReportH\x00R\rworkerMetrics\x12;\n" +
	"\fschema_drift\x18\t \x01(\v2\x16.urutau.v1.SchemaDriftH\x00R\vschemaDriftB\x05\n" +
	"\x03msg\"O\n" +
	"\vSchemaDrift\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x16\n" +
	"\x06column\x18\x02 \x01(\tR\x06column\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"\xc3\x01\n" +
	"\x12CoordinatorMessage\x12/\n" +
	"\x06assign\x18\x01 \x01(\v2\x15.urutau.v1.AssignmentH\x00R\x06assign\x12/\n" +
	"\x05chunk\x18\x02 \x01(\v2\x17.urutau.v1.ChunkRequestH\x00R\x05chunk\x12D\n" +
	"\vmaintenance\x18\x03 \x01(\v2 .urutau.v1.MaintenanceAssignmentH\x00R\vmaintenanceB\x05\n" +
	"\x03msg\"t\n" +
	"\x0eControlMessage\x12(\n" +
	"\x05pause\x18\x01 \x01(\v2\x10.urutau.v1.PauseH\x00R\x05pause\x121\n" +
	"\bshutdown\x18\x02 \x01(\v2\x13.urutau.v1.ShutdownH\x00R\bshutdownB\x05\n" +
	"\x03msg\"\xf2\x03\n" +
	"\x05Hello\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12\x17\n" +
	"\apod_uid\x18\x02 \x01(\tR\x06podUid\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12,\n" +
	"\x05phase\x18\x04 \x01(\x0e2\x16.urutau.v1.WorkerPhaseR\x05phase\x12!\n" +
	"\fimage_digest\x18\x05 \x01(\tR\vimageDigest\x12=\n" +
	"\tcommitted\x18\x06 \x03(\v2\x1f.urutau.v1.Hello.CommittedEntryR\tcommitted\x12P\n" +
	"\x10completed_chunks\x18\a \x03(\v2%.urutau.v1.Hello.CompletedChunksEntryR\x0fcompletedChunks\x12 \n" +
	"\vmaintenance\x18\b \x01(\bR\vmaintenance\x1a<\n" +
	"\x0eCommittedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aW\n" +
	"\x14CompletedChunksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.urutau.v1.ChunkIdsR\x05value:\x028\x01\"{\n" +
	"\x15MaintenanceAssignment\x12!\n" +
	"\ftarget_table\x18\x01 \x01(\tR\vtargetTable\x12\x10\n" +
	"\x03ops\x18\x02 \x03(\tR\x03ops\x12-\n" +
	"\x12maintenance_config\x18\x03 \x01(\fR\x11maintenanceConfig\"E\n" +
	"\x11MaintenanceResult\x120\n" +
	"\x03ops\x18\x01 \x03(\v2\x1e.urutau.v1.MaintenanceOpResultR\x03ops\"\xc0\x01\n" +
	"\x13MaintenanceOpResult\x12=\n" +
	"\n" +
	"compaction\x18\x01 \x01(\v2\x1b.urutau.v1.CompactionResultH\x00R\n" +
	"compaction\x121\n" +
	"\x06expiry\x18\x02 \x01(\v2\x17.urutau.v1.ExpiryResultH\x00R\x06expiry\x121\n" +
	"\x06orphan\x18\x03 \x01(\v2\x17.urutau.v1.OrphanResultH\x00R\x06orphanB\x04\n" +
	"\x02op\"\xb2\x01\n" +
	"\x10CompactionResult\x12#\n" +
	"\rfiles_removed\x18\x01 \x01(\x03R\ffilesRemoved\x12\x1f\n" +
	"\vfiles_added\x18\x02 \x01(\x03R\n" +
	"filesAdded\x12!\n" +
	"\fbytes_before\x18\x03 \x01(\x03R\vbytesBefore\x12\x1f\n" +
	"\vbytes_after\x18\x04 \x01(\x03R\n" +
	"bytesAfter\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"Q\n" +
	"\fExpiryResult\x12+\n" +
	"\x11snapshots_removed\x18\x01 \x01(\x03R\x10snapshotsRemoved\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"j\n" +
	"\fOrphanResult\x12#\n" +
	"\rfiles_deleted\x18\x01 \x01(\x03R\ffilesDeleted\x12\x1f\n" +
	"\vbytes_freed\x18\x02 \x01(\x03R\n" +
	"bytesFreed\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"F\n" +
	"\x13WorkerMetricsReport\x12/\n" +
	"\x06tables\x18\x01 \x03(\v2\x17.urutau.v1.TableMetricsR\x06tables\"\x81\x02\n" +
	"\fTableMetrics\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12'\n" +
	"\x0fcommit_failures\x18\x02 \x01(\x03R\x0ecommitFailures\x12'\n" +
	"\x0fdeletes_dropped\x18\x03 \x01(\x03R\x0edeletesDropped\x12+\n" +
	"\x11snapshot_progress\x18\x04 \x01(\x01R\x10snapshotProgress\x120\n" +
	"\x06enrich\x18\x05 \x03(\v2\x18.urutau.v1.EnrichMetricsR\x06enrich\x12*\n" +
	"\x11commit_latency_ms\x18\x06 \x01(\x01R\x0fcommitLatencyMs\"\x84\x01\n" +
	"\rEnrichMetrics\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\x12\x16\n" +
	"\x06misses\x18\x02 \x01(\x03R\x06misses\x12#\n" +
	"\rinner_dropped\x18\x03 \x01(\x03R\finnerDropped\x12\x18\n" +
	"\aevicted\x18\x04 \x01(\x03R\aevicted\"\x1c\n" +
	"\bChunkIds\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\rR\x03ids\"\xf4\x03\n" +
	"\tEnrichRef\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x02 \x01(\tR\tsourceUri\x12!\n" +
	"\fsource_query\x18\x03 \x01(\tR\vsourceQuery\x12,\n" +
	"\x02on\x18\x04 \x03(\v2\x1c.urutau.v1.EnrichRef.OnEntryR\x02on\x12\x16\n" +
	"\x06select\x18\x05 \x03(\tR\x06select\x12,\n" +
	"\x02as\x18\x06 \x03(\v2\x1c.urutau.v1.EnrichRef.AsEntryR\x02as\x12\x1b\n" +
	"\tjoin_type\x18\a \x01(\tR\bjoinType\x12\x18\n" +
	"\arefresh\x18\b \x01(\tR\arefresh\x12\"\n" +
	"\ron_cold_start\x18\t \x01(\tR\vonColdStart\x12*\n" +
	"\x11buffer_max_events\x18\n" +
	" \x01(\x03R\x0fbufferMaxEvents\x12&\n" +
	"\x0fbuffer_max_wait\x18\v \x01(\tR\rbufferMaxWait\x1a5\n" +
	"\aOnEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a5\n" +
	"\aAsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x04\n" +
	"\x0fTableAssignment\x12!\n" +
	"\fsource_table\x18\x01 \x01(\tR\vsourceTable\x12!\n" +
	"\ftarget_table\x18\x02 \x01(\tR\vtargetTable\x123\n" +
	"\n" +
	"write_mode\x18\x03 \x01(\x0e2\x14.urutau.v1.WriteModeR\twriteMode\x12\x1f\n" +
	"\vprimary_key\x18\x04 \x03(\tR\n" +
	"primaryKey\x12!\n" +
	"\fpartition_by\x18\x05 \x03(\tR\vpartitionBy\x12%\n" +
	"\x0einclude_before\x18\x06 \x01(\bR\rincludeBefore\x12/\n" +
	"\x14create_if_not_exists\x18\a \x01(\bR\x11createIfNotExists\x12!\n" +
	"\fschema_arrow\x18\b \x01(\fR\vschemaArrow\x12,\n" +
	"\x06enrich\x18\t \x03(\v2\x14.urutau.v1.EnrichRefR\x06enrich\x12\x1f\n" +
	"\vcast_policy\x18\n" +
	" \x01(\fR\n" +
	"castPolicy\x12\x1a\n" +
	"\bmetadata\x18\v \x01(\fR\bmetadata\x12\x16\n" +
	"\x06staged\x18\f \x01(\bR\x06staged\x12#\n" +
	"\rcolumn_filter\x18\r \x03(\tR\fcolumnFilter\x12\x16\n" +
	"\x06filter\x18\x0e \x01(\fR\x06filter\x12!\n" +
	"\fchunk_column\x18\x0f \x01(\tR\vchunkColumn\x12\x1b\n" +
	"\ton_delete\x18\x10 \x01(\tR\bonDelete\"h\n" +
	"\vBatchConfig\x12\x1b\n" +
	"\tmax_bytes\x18\x01 \x01(\x03R\bmaxBytes\x12<\n" +
	"\fmax_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vmaxInterval\"\xf6\x02\n" +
	"\n" +
	"Assignment\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x16\n" +
	"\x06ticket\x18\x04 \x01(\fR\x06ticket\x122\n" +
	"\x06tables\x18\x05 \x03(\v2\x1a.urutau.v1.TableAssignmentR\x06tables\x122\n" +
	"\bbatching\x18\x06 \x01(\v2\x16.urutau.v1.BatchConfigR\bbatching\x12\x1f\n" +
	"\vresume_from\x18\a \x01(\tR\n" +
	"resumeFrom\x12\x1f\n" +
	"\vsource_kind\x18\b \x01(\tR\n" +
	"sourceKind\x12\x1d\n" +
	"\n" +
	"source_dsn\x18\t \x01(\tR\tsourceDsn\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\n" +
	" \x01(\rR\tchunkSize\x12\x1a\n" +
	"\bpostgres\x18\v \x01(\fR\bpostgres\"\xda\x01\n" +
	"\x03Ack\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12\x12\n" +
	"\x04rows\x18\x05 \x01(\x04R\x04rows\x12\x18\n" +
	"\adeletes\x18\x06 \x01(\x04R\adeletes\x12B\n" +
	"\x0fcommit_duration\x18\a \x01(\v2\x19.google.protobuf.DurationR\x0ecommitDuration\"~\n" +
	"\fChunkRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\rR\achunkId\x12\x16\n" +
	"\x06bounds\x18\x03 \x01(\fR\x06bounds\x12%\n" +
	"\x0einclusive_high\x18\x04 \x01(\bR\rinclusiveHigh\"\x93\x01\n" +
	"\n" +
	"ChunkReady\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\rR\achunkId\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x04R\x04rows\x12*\n" +
	"\x11dropped_by_window\x18\x04 \x01(\x04R\x0fdroppedByWindow\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x04R\x05epoch\"\x83\x01\n" +
	"\vChunkFailed\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\rR\achunkId\x12+\n" +
	"\x05class\x18\x03 \x01(\x0e2\x15.urutau.v1.ErrorClassR\x05class\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\xd9\x01\n" +
	"\vStagedBatch\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x03 \x01(\fR\n" +
	"descriptor\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12%\n" +
	"\x0esnapshot_state\x18\x05 \x01(\tR\rsnapshotState\x12)\n" +
	"\x10snapshot_pending\x18\x06 \x03(\rR\x0fsnapshotPending\x12\x14\n" +
	"\x05epoch\x18\a \x01(\x04R\x05epoch\"|\n" +
	"\vWorkerError\x12+\n" +
	"\x05class\x18\x01 \x01(\x0e2\x15.urutau.v1.ErrorClassR\x05class\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x14\n" +
	"\x05table\x18\x04 \x01(\tR\x05table\"5\n" +
	"\x05Pause\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\"Q\n" +
	"\bShutdown\x12/\n" +
	"\x05grace\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05grace\x12\x14\n" +
	"\x05drain\x18\x02 \x01(\bR\x05drain\"\xcc\x01\n" +
	"\tBatchMeta\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x17\n" +
	"\alow_pos\x18\x02 \x01(\tR\x06lowPos\x12\x19\n" +
	"\bhigh_pos\x18\x03 \x01(\tR\ahighPos\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\x04R\abatchId\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x04R\x05epoch\x12,\n" +
	"\x06window\x18\x06 \x01(\v2\x14.urutau.v1.WindowTagR\x06window\x12\x16\n" +
	"\x06staged\x18\a \x01(\bR\x06staged\"\x9c\x01\n" +
	"\tWindowTag\x12\x1b\n" +
	"\tin_window\x18\x01 \x01(\bR\binWindow\x12\x16\n" +
	"\x06closes\x18\x02 \x01(\bR\x06closes\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\rR\achunkId\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\bR\bsnapshot\x12#\n" +
	"\rsnapshot_done\x18\x05 \x01(\bR\fsnapshotDone*\x81\x01\n" +
	"\vWorkerPhase\x12\x1c\n" +
	"\x18WORKER_PHASE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WORKER_PHASE_STARTING\x10\x01\x12\x1d\n" +
	"\x19WORKER_PHASE_SNAPSHOTTING\x10\x02\x12\x1a\n" +
	"\x16WORKER_PHASE_STREAMING\x10\x03*U\n" +
	"\tWriteMode\x12\x1a\n" +
	"\x16WRITE_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WRITE_MODE_UPSERT\x10\x01\x12\x15\n" +
	"\x11WRITE_MODE_APPEND\x10\x02*\x9a\x01\n" +
	"\n" +
	"ErrorClass\x12\x1b\n" +
	"\x17ERROR_CLASS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ERROR_CLASS_TRANSIENT\x10\x01\x12\x1c\n" +
	"\x18ERROR_CLASS_WORKER_FATAL\x10\x02\x12\x19\n" +
	"\x15ERROR_CLASS_JOB_FATAL\x10\x03\x12\x1b\n" +
	"\x17ERROR_CLASS_NEEDS_HUMAN\x10\x042\x9b\x01\n" +
	"\rUrutauControl\x12F\n" +
	"\aSession\x12\x18.urutau.v1.WorkerMessage\x1a\x1d.urutau.v1.CoordinatorMessage(\x010\x01\x12B\n" +
	"\aControl\x12\x18.urutau.v1.WorkerMessage\x1a\x19.urutau.v1.ControlMessage(\x010\x01B@Z>github.com/maltzsama/urutau/internal/transport/pb/urutau/v1;pbb\x06proto3"

var (
	file_urutau_v1_control_proto_rawDescOnce sync.Once
	file_urutau_v1_control_proto_rawDescData []byte
)

func file_urutau_v1_control_proto_rawDescGZIP() []byte {
	file_urutau_v1_control_proto_rawDescOnce.Do(func() {
		file_urutau_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_urutau_v1_control_proto_rawDesc), len(file_urutau_v1_control_proto_rawDesc)))
	})
	return file_urutau_v1_control_proto_rawDescData
}

var file_urutau_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_urutau_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_urutau_v1_control_proto_goTypes = []any{
	(WorkerPhase)(0),              // 0: urutau.v1.WorkerPhase
	(WriteMode)(0),                // 1: urutau.v1.WriteMode
	(ErrorClass)(0),               // 2: urutau.v1.ErrorClass
	(*WorkerMessage)(nil),         // 3: urutau.v1.WorkerMessage
	(*SchemaDrift)(nil),           // 4: urutau.v1.SchemaDrift
	(*CoordinatorMessage)(nil),    // 5: urutau.v1.CoordinatorMessage
	(*ControlMessage)(nil),        // 6: urutau.v1.ControlMessage
	(*Hello)(nil),                 // 7: urutau.v1.Hello
	(*MaintenanceAssignment)(nil), // 8: urutau.v1.MaintenanceAssignment
	(*MaintenanceResult)(nil),     // 9: urutau.v1.MaintenanceResult
	(*MaintenanceOpResult)(nil),   // 10: urutau.v1.MaintenanceOpResult
	(*CompactionResult)(nil),      // 11: urutau.v1.CompactionResult
	(*ExpiryResult)(nil),          // 12: urutau.v1.ExpiryResult
	(*OrphanResult)(nil),          // 13: urutau.v1.OrphanResult
	(*WorkerMetricsReport)(nil),   // 14: urutau.v1.WorkerMetricsReport
	(*TableMetrics)(nil),          // 15: urutau.v1.TableMetrics
	(*EnrichMetrics)(nil),         // 16: urutau.v1.EnrichMetrics
	(*ChunkIds)(nil),              // 17: urutau.v1.ChunkIds
	(*EnrichRef)(nil),             // 18: urutau.v1.EnrichRef
	(*TableAssignment)(nil),       // 19: urutau.v1.TableAssignment
	(*BatchConfig)(nil),           // 20: urutau.v1.BatchConfig
	(*Assignment)(nil),            // 21: urutau.v1.Assignment
	(*Ack)(nil),                   // 22: urutau.v1.Ack
	(*ChunkRequest)(nil),          // 23: urutau.v1.ChunkRequest
	(*ChunkReady)(nil),            // 24: urutau.v1.ChunkReady
	(*ChunkFailed)(nil),           // 25: urutau.v1.ChunkFailed
	(*StagedBatch)(nil),           // 26: urutau.v1.StagedBatch
	(*WorkerError)(nil),           // 27: urutau.v1.WorkerError
	(*Pause)(nil),                 // 28: urutau.v1.Pause
	(*Shutdown)(nil),              // 29: urutau.v1.Shutdown
	(*BatchMeta)(nil),             // 30: urutau.v1.BatchMeta
	(*WindowTag)(nil),             // 31: urutau.v1.WindowTag
	nil,                           // 32: urutau.v1.Hello.CommittedEntry
	nil,                           // 33: urutau.v1.Hello.CompletedChunksEntry
	nil,                           // 34: urutau.v1.EnrichRef.OnEntry
	nil,                           // 35: urutau.v1.EnrichRef.AsEntry
	(*durationpb.Duration)(nil),   // 36: google.protobuf.Duration
}
var file_urutau_v1_control_proto_depIdxs = []int32{
	7,  // 0: urutau.v1.WorkerMessage.hello:type_name -> urutau.v1.Hello
	22, // 1: urutau.v1.WorkerMessage.ack:type_name -> urutau.v1.Ack
	24, // 2: urutau.v1.WorkerMessage.chunk_ready:type_name -> urutau.v1.ChunkReady
	25, // 3: urutau.v1.WorkerMessage.chunk_failed:type_name -> urutau.v1.ChunkFailed
	27, // 4: urutau.v1.WorkerMessage.error:type_name -> urutau.v1.WorkerError
	26, // 5: urutau.v1.WorkerMessage.staged:type_name -> urutau.v1.StagedBatch
	9,  // 6: urutau.v1.WorkerMessage.maintenance_result:type_name -> urutau.v1.MaintenanceResult
	14, // 7: urutau.v1.WorkerMessage.worker_metrics:type_name -> urutau.v1.WorkerMetricsReport
	4,  // 8: urutau.v1.WorkerMessage.schema_drift:type_name -> urutau.v1.SchemaDrift
	21, // 9: urutau.v1.CoordinatorMessage.assign:type_name -> urutau.v1.Assignment
	23, // 10: urutau.v1.CoordinatorMessage.chunk:type_name -> urutau.v1.ChunkRequest
	8,  // 11: urutau.v1.CoordinatorMessage.maintenance:type_name -> urutau.v1.MaintenanceAssignment
	28, // 12: urutau.v1.ControlMessage.pause:type_name -> urutau.v1.Pause
	29, // 13: urutau.v1.ControlMessage.shutdown:type_name -> urutau.v1.Shutdown
	0,  // 14: urutau.v1.Hello.phase:type_name -> urutau.v1.WorkerPhase
	32, // 15: urutau.v1.Hello.committed:type_name -> urutau.v1.Hello.CommittedEntry
	33, // 16: urutau.v1.Hello.completed_chunks:type_name -> urutau.v1.Hello.CompletedChunksEntry
	10, // 17: urutau.v1.MaintenanceResult.ops:type_name -> urutau.v1.MaintenanceOpResult
	11, // 18: urutau.v1.MaintenanceOpResult.compaction:type_name -> urutau.v1.CompactionResult
	12, // 19: urutau.v1.MaintenanceOpResult.expiry:type_name -> urutau.v1.ExpiryResult
	13, // 20: urutau.v1.MaintenanceOpResult.orphan:type_name -> urutau.v1.OrphanResult
	15, // 21: urutau.v1.WorkerMetricsReport.tables:type_name -> urutau.v1.TableMetrics
	16, // 22: urutau.v1.TableMetrics.enrich:type_name -> urutau.v1.EnrichMetrics
	34, // 23: urutau.v1.EnrichRef.on:type_name -> urutau.v1.EnrichRef.OnEntry
	35, // 24: urutau.v1.EnrichRef.as:type_name -> urutau.v1.EnrichRef.AsEntry
	1,  // 25: urutau.v1.TableAssignment.write_mode:type_name -> urutau.v1.WriteMode
	18, // 26: urutau.v1.TableAssignment.enrich:type_name -> urutau.v1.EnrichRef
	36, // 27: urutau.v1.BatchConfig.max_interval:type_name -> google.protobuf.Duration
	19, // 28: urutau.v1.Assignment.tables:type_name -> urutau.v1.TableAssignment
	20, // 29: urutau.v1.Assignment.batching:type_name -> urutau.v1.BatchConfig
	36, // 30: urutau.v1.Ack.commit_duration:type_name -> google.protobuf.Duration
	2,  // 31: urutau.v1.ChunkFailed.class:type_name -> urutau.v1.ErrorClass
	2,  // 32: urutau.v1.WorkerError.class:type_name -> urutau.v1.ErrorClass
	36, // 33: urutau.v1.Shutdown.grace:type_name -> google.protobuf.Duration
	31, // 34: urutau.v1.BatchMeta.window:type_name -> urutau.v1.WindowTag
	17, // 35: urutau.v1.Hello.CompletedChunksEntry.value:type_name -> urutau.v1.ChunkIds
	3,  // 36: urutau.v1.UrutauControl.Session:input_type -> urutau.v1.WorkerMessage
	3,  // 37: urutau.v1.UrutauControl.Control:input_type -> urutau.v1.WorkerMessage
	5,  // 38: urutau.v1.UrutauControl.Session:output_type -> urutau.v1.CoordinatorMessage
	6,  // 39: urutau.v1.UrutauControl.Control:output_type -> urutau.v1.ControlMessage
	38, // [38:40] is the sub-list for method output_type
	36, // [36:38] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_urutau_v1_control_proto_init() }
func file_urutau_v1_control_proto_init() {
	if File_urutau_v1_control_proto != nil {
		return
	}
	file_urutau_v1_control_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Ack)(nil),
		(*WorkerMessage_ChunkReady)(nil),
		(*WorkerMessage_ChunkFailed)(nil),
		(*WorkerMessage_Error)(nil),
		(*WorkerMessage_Staged)(nil),
		(*WorkerMessage_MaintenanceResult)(nil),
		(*WorkerMessage_WorkerMetrics)(nil),
		(*WorkerMessage_SchemaDrift)(nil),
	}
	file_urutau_v1_control_proto_msgTypes[2].OneofWrappers = []any{
		(*CoordinatorMessage_Assign)(nil),
		(*CoordinatorMessage_Chunk)(nil),
		(*CoordinatorMessage_Maintenance)(nil),
	}
	file_urutau_v1_control_proto_msgTypes[3].OneofWrappers = []any{
		(*ControlMessage_Pause)(nil),
		(*ControlMessage_Shutdown)(nil),
	}
	file_urutau_v1_control_proto_msgTypes[7].OneofWrappers = []any{
		(*MaintenanceOpResult_Compaction)(nil),
		(*MaintenanceOpResult_Expiry)(nil),
		(*MaintenanceOpResult_Orphan)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_urutau_v1_control_proto_rawDesc), len(file_urutau_v1_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urutau_v1_control_proto_goTypes,
		DependencyIndexes: file_urutau_v1_control_proto_depIdxs,
		EnumInfos:         file_urutau_v1_control_proto_enumTypes,
		MessageInfos:      file_urutau_v1_control_proto_msgTypes,
	}.Build()
	File_urutau_v1_control_proto = out.File
	file_urutau_v1_control_proto_goTypes = nil
	file_urutau_v1_control_proto_depIdxs = nil
}
