// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: urutau/v1/urutau.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UrutauControl_Session_FullMethodName = "/urutau.v1.UrutauControl/Session"
	UrutauControl_Control_FullMethodName = "/urutau.v1.UrutauControl/Control"
)

// UrutauControlClient is the client API for UrutauControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Control plane: handshake, acks, and chunks. Carries NO data.
type UrutauControlClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, CoordinatorMessage], error)
	// Urgent signals on the SAME ClientConn — never queued behind data.
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ControlMessage], error)
}

type urutauControlClient struct {
	cc grpc.ClientConnInterface
}

func NewUrutauControlClient(cc grpc.ClientConnInterface) UrutauControlClient {
	return &urutauControlClient{cc}
}

func (c *urutauControlClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, CoordinatorMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UrutauControl_ServiceDesc.Streams[0], UrutauControl_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, CoordinatorMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UrutauControl_SessionClient = grpc.BidiStreamingClient[WorkerMessage, CoordinatorMessage]

func (c *urutauControlClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UrutauControl_ServiceDesc.Streams[1], UrutauControl_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UrutauControl_ControlClient = grpc.BidiStreamingClient[WorkerMessage, ControlMessage]

// UrutauControlServer is the server API for UrutauControl service.
// All implementations must embed UnimplementedUrutauControlServer
// for forward compatibility.
//
// Control plane: handshake, acks, and chunks. Carries NO data.
type UrutauControlServer interface {
	Session(grpc.BidiStreamingServer[WorkerMessage, CoordinatorMessage]) error
	// Urgent signals on the SAME ClientConn — never queued behind data.
	Control(grpc.BidiStreamingServer[WorkerMessage, ControlMessage]) error
	mustEmbedUnimplementedUrutauControlServer()
}

// UnimplementedUrutauControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUrutauControlServer struct{}

func (UnimplementedUrutauControlServer) Session(grpc.BidiStreamingServer[WorkerMessage, CoordinatorMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedUrutauControlServer) Control(grpc.BidiStreamingServer[WorkerMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedUrutauControlServer) mustEmbedUnimplementedUrutauControlServer() {}
func (UnimplementedUrutauControlServer) testEmbeddedByValue()                       {}

// UnsafeUrutauControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrutauControlServer will
// result in compilation errors.
type UnsafeUrutauControlServer interface {
	mustEmbedUnimplementedUrutauControlServer()
}

func RegisterUrutauControlServer(s grpc.ServiceRegistrar, srv UrutauControlServer) {
	// If the following call panics, it indicates UnimplementedUrutauControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UrutauControl_ServiceDesc, srv)
}

func _UrutauControl_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UrutauControlServer).Session(&grpc.GenericServerStream[WorkerMessage, CoordinatorMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UrutauControl_SessionServer = grpc.BidiStreamingServer[WorkerMessage, CoordinatorMessage]

func _UrutauControl_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UrutauControlServer).Control(&grpc.GenericServerStream[WorkerMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UrutauControl_ControlServer = grpc.BidiStreamingServer[WorkerMessage, ControlMessage]

// UrutauControl_ServiceDesc is the grpc.ServiceDesc for UrutauControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrutauControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "urutau.v1.UrutauControl",
	HandlerType: (*UrutauControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _UrutauControl_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Control",
			Handler:       _UrutauControl_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "urutau/v1/urutau.proto",
}
