// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: urutau/v1/urutau.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Ack
	//	*WorkerMessage_Chunk
	//	*WorkerMessage_Error
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *WorkerMessage) GetChunk() *ChunkReady {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *WorkerMessage) GetError() *WorkerError {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type WorkerMessage_Chunk struct {
	Chunk *ChunkReady `protobuf:"bytes,3,opt,name=chunk,proto3,oneof"`
}

type WorkerMessage_Error struct {
	Error *WorkerError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Msg() {}

func (*WorkerMessage_Ack) isWorkerMessage_Msg() {}

func (*WorkerMessage_Chunk) isWorkerMessage_Msg() {}

func (*WorkerMessage_Error) isWorkerMessage_Msg() {}

type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*CoordinatorMessage_Assign
	//	*CoordinatorMessage_Chunk
	Msg           isCoordinatorMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinatorMessage) GetMsg() isCoordinatorMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CoordinatorMessage) GetAssign() *Assignment {
	if x != nil {
		if x, ok := x.Msg.(*CoordinatorMessage_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetChunk() *ChunkRequest {
	if x != nil {
		if x, ok := x.Msg.(*CoordinatorMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isCoordinatorMessage_Msg interface {
	isCoordinatorMessage_Msg()
}

type CoordinatorMessage_Assign struct {
	Assign *Assignment `protobuf:"bytes,1,opt,name=assign,proto3,oneof"`
}

type CoordinatorMessage_Chunk struct {
	Chunk *ChunkRequest `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*CoordinatorMessage_Assign) isCoordinatorMessage_Msg() {}

func (*CoordinatorMessage_Chunk) isCoordinatorMessage_Msg() {}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControlMessage_Pause
	//	*ControlMessage_Shutdown
	Msg           isControlMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{2}
}

func (x *ControlMessage) GetMsg() isControlMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControlMessage) GetPause() *Pause {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *ControlMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isControlMessage_Msg interface {
	isControlMessage_Msg()
}

type ControlMessage_Pause struct {
	Pause *Pause `protobuf:"bytes,1,opt,name=pause,proto3,oneof"`
}

type ControlMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,2,opt,name=shutdown,proto3,oneof"`
}

func (*ControlMessage_Pause) isControlMessage_Msg() {}

func (*ControlMessage_Shutdown) isControlMessage_Msg() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerName    string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	PodUid        string                 `protobuf:"bytes,2,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`                                                                   // detects zombies
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`                                                                                  // bumped on every reset
	Committed     map[string]string      `protobuf:"bytes,4,rep,name=committed,proto3" json:"committed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // target_table → position
	ImageDigest   string                 `protobuf:"bytes,5,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`                                                    // detects image skew
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Hello) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *Hello) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Hello) GetCommitted() map[string]string {
	if x != nil {
		return x.Committed
	}
	return nil
}

func (x *Hello) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"` // position AFTER the Iceberg commit
	Rows          uint64                 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	CommitMs      int64                  `protobuf:"varint,5,opt,name=commit_ms,json=commitMs,proto3" json:"commit_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{4}
}

func (x *Ack) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *Ack) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Ack) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Ack) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Ack) GetCommitMs() int64 {
	if x != nil {
		return x.CommitMs
	}
	return 0
}

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerName    string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Tables        []string               `protobuf:"bytes,3,rep,name=tables,proto3" json:"tables,omitempty"` // target tables of this worker
	Ticket        []byte                 `protobuf:"bytes,4,opt,name=ticket,proto3" json:"ticket,omitempty"` // Flight DoGet ticket
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{5}
}

func (x *Assignment) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Assignment) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Assignment) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *Assignment) GetTicket() []byte {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	ChunkId       uint32                 `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Low           []byte                 `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`   // lower PK bound (lexicographic tuple)
	High          []byte                 `protobuf:"bytes,4,opt,name=high,proto3" json:"high,omitempty"` // upper PK bound
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ChunkRequest) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *ChunkRequest) GetLow() []byte {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *ChunkRequest) GetHigh() []byte {
	if x != nil {
		return x.High
	}
	return nil
}

type ChunkReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       uint32                 `protobuf:"varint,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Rows          uint64                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkReady) Reset() {
	*x = ChunkReady{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkReady) ProtoMessage() {}

func (x *ChunkReady) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkReady.ProtoReflect.Descriptor instead.
func (*ChunkReady) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkReady) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *ChunkReady) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type WorkerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerError) Reset() {
	*x = WorkerError{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerError) ProtoMessage() {}

func (x *WorkerError) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerError.ProtoReflect.Descriptor instead.
func (*WorkerError) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{8}
}

func (x *WorkerError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WorkerError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Pause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pause) Reset() {
	*x = Pause{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pause) ProtoMessage() {}

func (x *Pause) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pause.ProtoReflect.Descriptor instead.
func (*Pause) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{9}
}

func (x *Pause) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeadlineMs    int64                  `protobuf:"varint,1,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{10}
}

func (x *Shutdown) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

// Data plane: the FlightData body is raw Arrow IPC; BatchMeta travels in
// FlightData.app_metadata.
type BatchMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	LowPos        string                 `protobuf:"bytes,2,opt,name=low_pos,json=lowPos,proto3" json:"low_pos,omitempty"`
	HighPos       string                 `protobuf:"bytes,3,opt,name=high_pos,json=highPos,proto3" json:"high_pos,omitempty"`
	BatchId       uint64                 `protobuf:"varint,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Window        *WindowTag             `protobuf:"bytes,5,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMeta) Reset() {
	*x = BatchMeta{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMeta) ProtoMessage() {}

func (x *BatchMeta) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMeta.ProtoReflect.Descriptor instead.
func (*BatchMeta) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{11}
}

func (x *BatchMeta) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *BatchMeta) GetLowPos() string {
	if x != nil {
		return x.LowPos
	}
	return ""
}

func (x *BatchMeta) GetHighPos() string {
	if x != nil {
		return x.HighPos
	}
	return ""
}

func (x *BatchMeta) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *BatchMeta) GetWindow() *WindowTag {
	if x != nil {
		return x.Window
	}
	return nil
}

type WindowTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InWindow      bool                   `protobuf:"varint,1,opt,name=in_window,json=inWindow,proto3" json:"in_window,omitempty"`
	Closes        bool                   `protobuf:"varint,2,opt,name=closes,proto3" json:"closes,omitempty"`
	ChunkId       uint32                 `protobuf:"varint,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowTag) Reset() {
	*x = WindowTag{}
	mi := &file_urutau_v1_urutau_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowTag) ProtoMessage() {}

func (x *WindowTag) ProtoReflect() protoreflect.Message {
	mi := &file_urutau_v1_urutau_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowTag.ProtoReflect.Descriptor instead.
func (*WindowTag) Descriptor() ([]byte, []int) {
	return file_urutau_v1_urutau_proto_rawDescGZIP(), []int{12}
}

func (x *WindowTag) GetInWindow() bool {
	if x != nil {
		return x.InWindow
	}
	return false
}

func (x *WindowTag) GetCloses() bool {
	if x != nil {
		return x.Closes
	}
	return false
}

func (x *WindowTag) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

var File_urutau_v1_urutau_proto protoreflect.FileDescriptor

const file_urutau_v1_urutau_proto_rawDesc = "" +
	"\n" +
	"\x16urutau/v1/urutau.proto\x12\turutau.v1\"\xc3\x01\n" +
	"\rWorkerMessage\x12(\n" +
	"\x05hello\x18\x01 \x01(\v2\x10.urutau.v1.HelloH\x00R\x05hello\x12\"\n" +
	"\x03ack\x18\x02 \x01(\v2\x0e.urutau.v1.AckH\x00R\x03ack\x12-\n" +
	"\x05chunk\x18\x03 \x01(\v2\x15.urutau.v1.ChunkReadyH\x00R\x05chunk\x12.\n" +
	"\x05error\x18\x04 \x01(\v2\x16.urutau.v1.WorkerErrorH\x00R\x05errorB\x05\n" +
	"\x03msg\"}\n" +
	"\x12CoordinatorMessage\x12/\n" +
	"\x06assign\x18\x01 \x01(\v2\x15.urutau.v1.AssignmentH\x00R\x06assign\x12/\n" +
	"\x05chunk\x18\x02 \x01(\v2\x17.urutau.v1.ChunkRequestH\x00R\x05chunkB\x05\n" +
	"\x03msg\"t\n" +
	"\x0eControlMessage\x12(\n" +
	"\x05pause\x18\x01 \x01(\v2\x10.urutau.v1.PauseH\x00R\x05pause\x121\n" +
	"\bshutdown\x18\x02 \x01(\v2\x13.urutau.v1.ShutdownH\x00R\bshutdownB\x05\n" +
	"\x03msg\"\xf7\x01\n" +
	"\x05Hello\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12\x17\n" +
	"\apod_uid\x18\x02 \x01(\tR\x06podUid\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12=\n" +
	"\tcommitted\x18\x04 \x03(\v2\x1f.urutau.v1.Hello.CommittedEntryR\tcommitted\x12!\n" +
	"\fimage_digest\x18\x05 \x01(\tR\vimageDigest\x1a<\n" +
	"\x0eCommittedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x03Ack\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x04R\x04rows\x12\x1b\n" +
	"\tcommit_ms\x18\x05 \x01(\x03R\bcommitMs\"s\n" +
	"\n" +
	"Assignment\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x16\n" +
	"\x06tables\x18\x03 \x03(\tR\x06tables\x12\x16\n" +
	"\x06ticket\x18\x04 \x01(\fR\x06ticket\"e\n" +
	"\fChunkRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\rR\achunkId\x12\x10\n" +
	"\x03low\x18\x03 \x01(\fR\x03low\x12\x12\n" +
	"\x04high\x18\x04 \x01(\fR\x04high\";\n" +
	"\n" +
	"ChunkReady\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\rR\achunkId\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x04R\x04rows\"9\n" +
	"\vWorkerError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x1f\n" +
	"\x05Pause\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"+\n" +
	"\bShutdown\x12\x1f\n" +
	"\vdeadline_ms\x18\x01 \x01(\x03R\n" +
	"deadlineMs\"\x9e\x01\n" +
	"\tBatchMeta\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x17\n" +
	"\alow_pos\x18\x02 \x01(\tR\x06lowPos\x12\x19\n" +
	"\bhigh_pos\x18\x03 \x01(\tR\ahighPos\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\x04R\abatchId\x12,\n" +
	"\x06window\x18\x05 \x01(\v2\x14.urutau.v1.WindowTagR\x06window\"[\n" +
	"\tWindowTag\x12\x1b\n" +
	"\tin_window\x18\x01 \x01(\bR\binWindow\x12\x16\n" +
	"\x06closes\x18\x02 \x01(\bR\x06closes\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\rR\achunkId2\x9b\x01\n" +
	"\rUrutauControl\x12F\n" +
	"\aSession\x12\x18.urutau.v1.WorkerMessage\x1a\x1d.urutau.v1.CoordinatorMessage(\x010\x01\x12B\n" +
	"\aControl\x12\x18.urutau.v1.WorkerMessage\x1a\x19.urutau.v1.ControlMessage(\x010\x01B@Z>github.com/maltzsama/urutau/internal/transport/pb/urutau/v1;pbb\x06proto3"

var (
	file_urutau_v1_urutau_proto_rawDescOnce sync.Once
	file_urutau_v1_urutau_proto_rawDescData []byte
)

func file_urutau_v1_urutau_proto_rawDescGZIP() []byte {
	file_urutau_v1_urutau_proto_rawDescOnce.Do(func() {
		file_urutau_v1_urutau_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_urutau_v1_urutau_proto_rawDesc), len(file_urutau_v1_urutau_proto_rawDesc)))
	})
	return file_urutau_v1_urutau_proto_rawDescData
}

var file_urutau_v1_urutau_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_urutau_v1_urutau_proto_goTypes = []any{
	(*WorkerMessage)(nil),      // 0: urutau.v1.WorkerMessage
	(*CoordinatorMessage)(nil), // 1: urutau.v1.CoordinatorMessage
	(*ControlMessage)(nil),     // 2: urutau.v1.ControlMessage
	(*Hello)(nil),              // 3: urutau.v1.Hello
	(*Ack)(nil),                // 4: urutau.v1.Ack
	(*Assignment)(nil),         // 5: urutau.v1.Assignment
	(*ChunkRequest)(nil),       // 6: urutau.v1.ChunkRequest
	(*ChunkReady)(nil),         // 7: urutau.v1.ChunkReady
	(*WorkerError)(nil),        // 8: urutau.v1.WorkerError
	(*Pause)(nil),              // 9: urutau.v1.Pause
	(*Shutdown)(nil),           // 10: urutau.v1.Shutdown
	(*BatchMeta)(nil),          // 11: urutau.v1.BatchMeta
	(*WindowTag)(nil),          // 12: urutau.v1.WindowTag
	nil,                        // 13: urutau.v1.Hello.CommittedEntry
}
var file_urutau_v1_urutau_proto_depIdxs = []int32{
	3,  // 0: urutau.v1.WorkerMessage.hello:type_name -> urutau.v1.Hello
	4,  // 1: urutau.v1.WorkerMessage.ack:type_name -> urutau.v1.Ack
	7,  // 2: urutau.v1.WorkerMessage.chunk:type_name -> urutau.v1.ChunkReady
	8,  // 3: urutau.v1.WorkerMessage.error:type_name -> urutau.v1.WorkerError
	5,  // 4: urutau.v1.CoordinatorMessage.assign:type_name -> urutau.v1.Assignment
	6,  // 5: urutau.v1.CoordinatorMessage.chunk:type_name -> urutau.v1.ChunkRequest
	9,  // 6: urutau.v1.ControlMessage.pause:type_name -> urutau.v1.Pause
	10, // 7: urutau.v1.ControlMessage.shutdown:type_name -> urutau.v1.Shutdown
	13, // 8: urutau.v1.Hello.committed:type_name -> urutau.v1.Hello.CommittedEntry
	12, // 9: urutau.v1.BatchMeta.window:type_name -> urutau.v1.WindowTag
	0,  // 10: urutau.v1.UrutauControl.Session:input_type -> urutau.v1.WorkerMessage
	0,  // 11: urutau.v1.UrutauControl.Control:input_type -> urutau.v1.WorkerMessage
	1,  // 12: urutau.v1.UrutauControl.Session:output_type -> urutau.v1.CoordinatorMessage
	2,  // 13: urutau.v1.UrutauControl.Control:output_type -> urutau.v1.ControlMessage
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_urutau_v1_urutau_proto_init() }
func file_urutau_v1_urutau_proto_init() {
	if File_urutau_v1_urutau_proto != nil {
		return
	}
	file_urutau_v1_urutau_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Ack)(nil),
		(*WorkerMessage_Chunk)(nil),
		(*WorkerMessage_Error)(nil),
	}
	file_urutau_v1_urutau_proto_msgTypes[1].OneofWrappers = []any{
		(*CoordinatorMessage_Assign)(nil),
		(*CoordinatorMessage_Chunk)(nil),
	}
	file_urutau_v1_urutau_proto_msgTypes[2].OneofWrappers = []any{
		(*ControlMessage_Pause)(nil),
		(*ControlMessage_Shutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_urutau_v1_urutau_proto_rawDesc), len(file_urutau_v1_urutau_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urutau_v1_urutau_proto_goTypes,
		DependencyIndexes: file_urutau_v1_urutau_proto_depIdxs,
		MessageInfos:      file_urutau_v1_urutau_proto_msgTypes,
	}.Build()
	File_urutau_v1_urutau_proto = out.File
	file_urutau_v1_urutau_proto_goTypes = nil
	file_urutau_v1_urutau_proto_depIdxs = nil
}
