import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Curated, not autogenerated: the order here is the order a reader should
// meet the material — run one pipeline, understand the model, then the
// how-tos, then the contracts, then the internals. Adding a page means
// adding it here.
const sidebars: SidebarsConfig = {
  docs: [
    'quickstart',
    'concepts',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/cdc-upsert',
        'guides/append-only',
        'guides/enrich-reference-table',
        'guides/plugins',
        'guides/distributed',
        'guides/deploy-kubernetes',
        'guides/monitoring',
        'guides/dashboard',
        'guides/reliability',
        'guides/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/guarantees',
        'reference/pipeline-spec',
        'reference/sources',
        'reference/sinks',
        'reference/dashboard-api',
        'reference/enrichment',
        'reference/cli',
        'reference/plugin-contract',
        'reference/roadmap',
        'reference/whats-new-v0.2.0',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/overview',
        'architecture/operator',
        'architecture/encode-key',
        'architecture/state-position',
        'architecture/enrich-internals',
      ],
    },
  ],
};

export default sidebars;
