import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Curated, not autogenerated: the order here is the order a reader should
// meet the material — get one pipeline running, then the how-tos, then the
// contracts, then the internals. Adding a page means adding it here.
const sidebars: SidebarsConfig = {
  docs: [
    'quickstart',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/cdc-upsert',
        'guides/append-only',
        'guides/enrich-reference-table',
        'guides/plugins',
        'guides/distributed',
        'guides/deploy-kubernetes',
        'guides/operations',
        'guides/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/semantics',
        'reference/spec',
        'reference/sources',
        'reference/sinks',
        'reference/enrichment',
        'reference/cli',
        'reference/plugin-contract',
        'reference/roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/overview',
        'architecture/operator',
        'architecture/encode-key',
        'architecture/state-position',
      ],
    },
  ],
};

export default sidebars;
